In [4]:
import pandas as pd
#https://docs.google.com/spreadsheets/d/1FPaF_fgOJIEdoJEWS2JS2rlnuyaa1Bl2LZdKUl9egwo/edit?usp=sharing

In [17]:

Zip_Zhvi_AllHomes = pd.read_csv('http://files.zillowstatic.com/research/public/Zip/Zip_Zhvi_AllHomes.csv')
#Zip_Zhvi_AllHomes.iloc[1,:]

RegionID        84654
RegionName      60657
City          Chicago
State              IL
Metro         Chicago
CountyName       Cook
SizeRank            2
1996-04        146700
1996-05        146500
1996-06        146300
1996-07        146300
1996-08        146800
1996-09        147100
1996-10        147300
1996-11        147800
1996-12        148600
1997-01        149100
1997-02        149600
1997-03        151100
1997-04        153200
1997-05        155100
1997-06        157200
1997-07        159100
1997-08        160000
1997-09        160800
1997-10        162200
1997-11        163200
1997-12        164100
1998-01        165600
1998-02        167400
               ...
2015-08        308300
2015-09        308500
2015-10        310100
2015-11        311100
2015-12        310500
2016-01        310900
2016-02        312200
2016-03        314000
2016-04        316100
2016-05        316700
2016-06        316600
2016-07        316500
2016-08        316800
2016-09        316400
2016-10        316300
2016-11        316800
2016-12        318300
2017-01        319000
2017-02        319900
2017-03        321200
2017-04        323000
2017-05        324600
2017-06        325200
2017-07        324300
2017-08        324000
2017-09        324500
2017-10        324200
2017-11        322500
2017-12        320400
2018-01        319700
Name: 1, Length: 269, dtype: object

In [68]:
Zip_Zhvi_AllHomesT= Zip_Zhvi_AllHomes.transpose()
 #.iloc[0,:]
#df.drop()
Zip_Zhvi_AllHomesT.drop(Zip_Zhvi_AllHomesT.index[2:7], inplace= True)
Zip_Zhvi_AllHomesT.drop(Zip_Zhvi_AllHomesT.index[0], inplace= True)
Zip_Zhvi_AllHomesT.columns = Zip_Zhvi_AllHomesT.iloc[0]
Zip_Zhvi_AllHomesT.drop(Zip_Zhvi_AllHomesT.index[0], inplace= True)
Zip_Zhvi_AllHomesT = Zip_Zhvi_AllHomesT.pct_change()

Zip_Zhvi_AllHomesT = Zip_Zhvi_AllHomesT.reset_index()

#>>> pd.melt(df, id_vars=['A'], value_vars=['B', 'C'])
Zip_Zhvi_AllHomesT

RegionName,index,10025,60657,60614,79936,60640,10467,77084,94109,75070,...,12429,54844,97028,12720,1338,97102,36564,3293,21405,85220
0,1996-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996-05,NaN,-0.001363,-0.012626,0.002825,-0.009775,NaN,-0.002646,-0.008384,NaN,...,0.001326,-0.000498,NaN,-0.007299,-0.008089,NaN,NaN,0.013228,0.001972,NaN
2,1996-06,NaN,-0.001365,-0.006650,0.000000,-0.005923,NaN,-0.003979,0.002367,NaN,...,0.003974,0.000498,NaN,0.026471,-0.003058,NaN,NaN,0.031332,0.005118,NaN
3,1996-07,NaN,0.000000,-0.002060,0.005634,-0.000993,NaN,0.000000,0.007085,NaN,...,0.006596,0.000000,NaN,0.008596,-0.002045,NaN,NaN,0.000000,0.011359,NaN
4,1996-08,NaN,0.003418,0.000516,-0.002801,0.000994,NaN,-0.002663,0.001005,NaN,...,0.011796,-0.000498,NaN,-0.048295,-0.007172,NaN,NaN,-0.043038,0.010844,NaN
5,1996-09,NaN,0.002044,0.003094,0.005618,0.005958,NaN,-0.002670,0.000335,NaN,...,0.003886,0.000000,NaN,-0.073134,-0.005160,NaN,NaN,-0.037037,0.009195,NaN
6,1996-10,NaN,0.001360,0.007198,0.013966,0.009872,NaN,-0.001339,-0.000669,NaN,...,-0.001290,0.000000,NaN,-0.032206,-0.004149,NaN,NaN,-0.021978,0.013667,NaN
7,1996-11,NaN,0.003394,0.010209,0.006887,0.008798,NaN,0.005362,-0.005022,NaN,...,-0.005168,0.000498,NaN,-0.011647,0.001042,NaN,NaN,-0.018258,0.029213,NaN
8,1996-12,NaN,0.005413,0.011117,-0.004104,0.011628,NaN,0.006667,0.002019,NaN,...,0.000000,0.000000,NaN,0.000000,0.005203,NaN,NaN,-0.001431,0.027293,NaN
9,1997-01,NaN,0.003365,-0.001999,0.000000,0.007663,NaN,0.006623,0.017126,NaN,...,0.007792,0.000000,NaN,0.006734,0.004141,NaN,NaN,0.005731,0.012044,NaN
10,1997-02,NaN,0.003353,-0.010015,0.001374,0.003802,NaN,0.003947,0.024100,0.011303,...,0.009021,0.000000,NaN,0.015050,-0.002062,NaN,NaN,-0.009972,-0.000350,NaN
11,1997-03,NaN,0.010027,-0.000506,0.002743,0.007576,NaN,0.005242,0.015152,0.000657,...,0.003831,0.000000,NaN,0.014827,0.001033,NaN,NaN,-0.010072,0.000350,NaN
12,1997-04,NaN,0.013898,0.010628,0.000000,0.003759,NaN,0.006519,0.011115,0.000657,...,-0.008906,0.000000,NaN,0.011364,0.003096,NaN,NaN,0.001453,-0.000350,NaN
13,1997-05,NaN,0.012402,0.004006,0.002736,-0.001873,NaN,0.007772,0.013191,0.000657,...,-0.010270,-0.000498,NaN,0.006421,0.006173,NaN,NaN,0.000000,0.005602,NaN
14,1997-06,NaN,0.013540,0.002494,0.002729,0.002814,NaN,0.006427,0.013019,0.000000,...,-0.001297,0.000498,NaN,0.009569,-0.002045,NaN,NaN,-0.008708,0.005919,NaN
15,1997-07,NaN,0.012087,0.005473,0.005442,0.009355,NaN,0.007663,0.014382,0.001312,...,0.001299,0.000000,NaN,0.022117,-0.003074,NaN,NaN,-0.002928,0.003461,NaN
16,1997-08,NaN,0.005657,0.002969,0.008119,0.011121,NaN,0.007605,0.018401,0.002621,...,-0.009079,-0.000498,NaN,0.034003,-0.002055,NaN,NaN,0.007342,0.001035,NaN
17,1997-09,NaN,0.005000,-0.001973,0.005369,0.004583,NaN,0.006289,0.006517,0.007843,...,-0.003927,0.000000,NaN,0.020927,0.003090,NaN,NaN,0.020408,0.006892,NaN
18,1997-10,NaN,0.008706,0.000989,0.004005,-0.005474,NaN,0.002500,0.000883,0.005837,...,0.000000,0.000000,NaN,0.008785,0.009240,NaN,NaN,0.021429,0.001027,NaN
19,1997-11,NaN,0.006165,0.002469,0.002660,-0.007339,NaN,0.002494,0.017054,0.003224,...,-0.002628,0.000000,NaN,-0.002903,0.009156,NaN,NaN,0.005594,-0.002051,NaN
20,1997-12,NaN,0.005515,0.000985,0.005305,-0.002773,NaN,0.001244,0.023706,0.004499,...,-0.001318,0.000498,NaN,-0.010189,0.005040,NaN,NaN,-0.002782,0.008222,NaN
21,1998-01,NaN,0.009141,0.002953,0.005277,0.000000,NaN,0.001242,0.012991,0.008957,...,0.005277,0.000000,NaN,-0.013235,0.006018,NaN,NaN,0.008368,0.025144,NaN
22,1998-02,NaN,0.010870,0.006869,0.003937,0.000927,NaN,0.001241,0.014497,0.007609,...,0.006562,0.000000,NaN,-0.004471,0.008973,NaN,NaN,0.001383,0.013921,NaN
23,1998-03,NaN,0.003584,0.008285,0.002614,0.008333,NaN,0.002478,0.022534,0.004405,...,0.014342,0.000000,NaN,0.005988,0.003953,NaN,NaN,-0.016575,0.003269,0.003645
24,1998-04,NaN,0.000595,0.010633,-0.002608,0.018365,NaN,0.003708,0.020156,-0.001253,...,0.016710,0.000000,NaN,0.007440,0.002953,NaN,NaN,-0.025281,0.011730,-0.001211
25,1998-05,NaN,0.002380,0.008608,-0.001307,0.017133,NaN,0.004926,0.016860,-0.003764,...,0.018963,0.000000,NaN,-0.004431,0.007851,NaN,NaN,-0.010086,0.021578,-0.001212
26,1998-06,NaN,0.002374,0.013276,0.001309,0.011525,NaN,0.004902,0.016580,-0.006297,...,0.009926,0.000000,NaN,-0.026706,0.014606,NaN,NaN,-0.002911,0.013556,0.000000
27,1998-07,NaN,0.001184,0.017314,-0.002614,0.011394,NaN,0.007317,0.019113,-0.007605,...,-0.004914,0.000000,NaN,-0.021341,0.011516,NaN,NaN,0.018978,0.000311,0.004854
28,1998-08,NaN,0.006505,0.014719,-0.002621,0.008666,NaN,0.006053,0.017754,-0.003193,...,-0.011111,-0.000498,NaN,-0.001558,0.009488,NaN,NaN,0.031519,-0.001244,-0.002415
29,1998-09,NaN,0.011163,0.007253,-0.002628,0.005155,NaN,0.004813,0.013514,0.001922,...,-0.001248,0.000000,NaN,0.020281,0.006579,NaN,NaN,0.030556,0.001868,-0.007264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,2015-08,0.018515,-0.001619,0.007283,0.000000,-0.006234,-0.006873,0.006338,0.011413,0.007105,...,-0.014277,0.010160,-0.003093,0.010142,0.004771,0.011022,0.010469,0.000000,-0.001362,0.008855
233,2015-09,0.021567,0.000649,0.018632,0.000000,0.004182,0.002517,0.009097,0.002799,0.008169,...,-0.011335,-0.004310,-0.007757,0.019076,0.000475,0.008792,0.004583,-0.002435,-0.003844,0.015214
234,2015-10,0.006635,0.005186,0.030576,0.000895,0.009891,0.002510,0.009709,0.002071,0.006630,...,-0.007643,-0.013709,-0.006567,0.018719,-0.004746,-0.000697,0.001785,-0.007322,-0.005975,0.017291
235,2015-11,0.001997,0.003225,0.020927,-0.001789,0.004639,0.001252,0.008242,0.005301,0.006220,...,0.002567,0.018288,-0.001574,0.013540,-0.006199,0.004710,0.013265,-0.010449,-0.001377,0.009632
236,2015-12,0.010864,-0.001929,0.009860,-0.002688,0.000513,0.005314,0.006812,0.009115,0.008000,...,0.010243,0.028017,0.002207,0.015267,0.000000,0.018750,0.019539,0.003727,0.002633,0.006173
237,2016-01,0.013410,0.001288,0.008222,-0.000898,0.001538,0.009639,0.006766,0.011778,0.010823,...,0.010139,0.007687,-0.003146,0.015038,0.003359,0.019257,0.006324,0.011139,-0.002001,0.002231
238,2016-02,0.019167,0.004181,0.009684,0.000000,0.000512,0.010779,0.010081,0.005864,0.011420,...,0.010665,0.007628,-0.001262,0.008333,0.000478,0.028256,-0.002285,0.007956,-0.007018,-0.006678
239,2016-03,0.018902,0.005766,0.007824,0.000000,-0.001535,0.010664,0.005988,-0.004003,0.008821,...,0.008690,0.014453,0.005055,0.001837,-0.005258,0.027967,-0.003818,0.003036,-0.007067,-0.011204
240,2016-04,0.003467,0.006688,0.008515,0.002698,0.002050,0.006934,0.006614,-0.011532,0.005946,...,0.008615,0.006784,0.010688,0.004583,-0.008650,0.011547,-0.003066,0.009080,-0.002034,-0.006799
241,2016-05,-0.004015,0.001898,-0.000993,0.004484,0.000000,0.006287,0.008541,-0.015556,0.006954,...,0.001830,-0.002695,0.005599,0.003650,-0.004847,-0.006880,-0.007111,0.009598,0.003821,-0.005134
242,2016-06,0.007687,-0.000316,-0.005966,0.004464,0.008696,0.004165,0.020195,-0.013647,0.010704,...,0.001218,-0.002027,-0.003712,-0.003636,-0.000487,-0.017163,-0.010453,0.008318,-0.001142,-0.000573
243,2016-07,0.015071,-0.000316,-0.004501,0.006222,0.008114,0.011852,0.021711,-0.003550,0.010591,...,0.006083,-0.001354,-0.006209,-0.010036,0.000000,-0.022269,-0.011541,0.002357,-0.000889,0.004016
244,2016-08,0.015672,0.000948,0.000000,0.004417,-0.001006,0.021962,0.007500,0.003654,0.006761,...,0.009069,0.000000,-0.004374,-0.010138,0.005361,-0.008029,-0.013259,-0.000588,0.002670,0.003429
245,2016-09,0.004151,-0.001263,0.003266,0.000000,-0.005539,0.019198,-0.004963,0.003914,0.003694,...,0.003595,0.003390,-0.003765,-0.009311,0.011634,0.006442,-0.012635,0.004118,0.001268,0.003417
246,2016-10,-0.000180,-0.000316,0.011017,0.000880,0.002532,0.007591,-0.001247,0.004080,0.005688,...,0.001791,0.004054,-0.004724,-0.007519,0.008625,0.018054,-0.006500,0.010545,-0.003039,0.006810
247,2016-11,0.015729,0.001581,0.021050,0.003515,0.004040,0.001395,0.000000,0.008307,0.007319,...,0.004172,-0.001346,0.000000,-0.009470,0.002850,0.019507,-0.005111,0.012754,-0.005843,0.009019
248,2016-12,0.007875,0.004735,0.008732,0.003503,0.006539,-0.003065,-0.007491,0.007970,0.004954,...,0.002374,-0.003369,-0.004747,-0.007648,0.006158,0.015655,0.009864,0.003434,-0.001150,0.007263
249,2017-01,-0.009658,0.002199,-0.000962,0.003490,0.008496,-0.002795,-0.013208,0.003287,0.003615,...,0.000000,-0.006085,-0.015580,-0.002890,0.007062,0.013234,0.020350,-0.005134,-0.002174,0.008319
250,2017-02,-0.007270,0.002821,0.000963,0.000000,0.009911,0.005325,-0.014022,0.002125,0.006221,...,0.003552,-0.006122,-0.014858,0.000966,0.006078,-0.003995,0.025728,-0.009174,-0.012819,0.008251
251,2017-03,0.002679,0.004064,-0.012503,-0.001739,0.006869,0.010315,-0.007757,0.004506,0.008135,...,0.010029,-0.004107,-0.003607,0.008687,0.006506,-0.024529,0.021194,-0.013310,-0.012206,0.005456
252,2017-04,0.017367,0.005604,-0.026297,-0.000871,-0.001462,0.008278,0.005212,0.008181,0.007747,...,0.007009,-0.011684,0.001645,0.017225,0.008310,-0.020244,0.017708,-0.014076,0.002761,0.000543
253,2017-05,0.041058,0.004954,0.004251,0.000872,-0.002928,0.003558,0.016850,0.006369,0.007367,...,0.006961,-0.015994,0.011827,0.014111,0.005495,-0.016142,0.005613,0.001190,0.011930,0.002711
254,2017-06,0.051379,0.001848,0.021912,-0.002613,0.000979,0.002454,0.010198,0.003641,0.003180,...,0.005760,-0.002827,0.020455,0.003711,0.002732,-0.015751,0.004837,0.011884,0.009328,0.008112
255,2017-07,0.035671,-0.002768,0.001462,-0.002620,0.008313,0.002448,0.005678,-0.001987,-0.000317,...,0.000573,0.012757,0.020999,0.000924,-0.000454,0.003834,0.003518,0.007046,0.002824,0.012339
256,2017-08,0.008109,-0.000925,-0.006326,0.000876,0.012124,0.007870,0.010038,-0.002077,0.002536,...,-0.001717,0.015395,0.014646,0.003693,0.000454,0.022252,-0.008487,0.000000,-0.004992,0.011129
257,2017-09,-0.006588,0.001543,-0.004163,0.004374,0.006229,0.014540,0.009317,0.005031,0.008855,...,0.009174,0.012405,0.005835,0.004600,0.003179,0.013320,-0.021585,-0.003499,-0.005403,0.004193
258,2017-10,-0.005167,-0.000924,-0.010327,0.000871,-0.002857,0.011146,0.002462,0.011737,0.007210,...,0.016477,0.002042,-0.000916,0.008242,0.003622,0.006092,-0.024344,-0.007022,0.000129,-0.001044
259,2017-11,-0.015038,-0.005244,-0.016646,-0.002611,-0.001910,0.007612,-0.001842,0.011089,0.001556,...,0.007267,-0.008832,0.001222,0.019982,0.010374,0.008126,-0.001949,-0.001768,0.000905,-0.005225
260,2017-12,-0.026363,-0.006512,-0.006316,-0.000873,0.000957,0.004168,-0.001845,0.001350,-0.000622,...,-0.002775,-0.003427,0.003053,0.020481,-0.010714,0.004742,0.003125,0.005313,-0.009302,-0.003676
261,2018-01,-0.019964,-0.002185,0.003814,0.002620,0.003824,-0.001816,0.000616,-0.005645,0.000311,...,-0.002226,0.002063,-0.000304,0.007853,-0.028430,0.001416,-0.004868,0.002936,-0.006781,0.002636

In [69]:
#Zip_Zhvi_AllHomes.count()

In [70]:
Zip_Zhvi_AllHomesT = pd.melt(Zip_Zhvi_AllHomesT,  id_vars='index', var_name='zip', value_name='price')
Zip_Zhvi_AllHomesT

           index    zip     price
0        1996-04  10025       NaN
1        1996-05  10025       NaN
2        1996-06  10025       NaN
3        1996-07  10025       NaN
4        1996-08  10025       NaN
5        1996-09  10025       NaN
6        1996-10  10025       NaN
7        1996-11  10025       NaN
8        1996-12  10025       NaN
9        1997-01  10025       NaN
10       1997-02  10025       NaN
11       1997-03  10025       NaN
12       1997-04  10025       NaN
13       1997-05  10025       NaN
14       1997-06  10025       NaN
15       1997-07  10025       NaN
16       1997-08  10025       NaN
17       1997-09  10025       NaN
18       1997-10  10025       NaN
19       1997-11  10025       NaN
20       1997-12  10025       NaN
21       1998-01  10025       NaN
22       1998-02  10025       NaN
23       1998-03  10025       NaN
24       1998-04  10025       NaN
25       1998-05  10025       NaN
26       1998-06  10025       NaN
27       1998-07  10025       NaN
28       1998-08  10025       NaN
29       1998-09  10025       NaN
...          ...    ...       ...
4015644  2015-08  85220  0.008855
4015645  2015-09  85220  0.015214
4015646  2015-10  85220  0.017291
4015647  2015-11  85220  0.009632
4015648  2015-12  85220  0.006173
4015649  2016-01  85220  0.002231
4015650  2016-02  85220 -0.006678
4015651  2016-03  85220 -0.011204
4015652  2016-04  85220 -0.006799
4015653  2016-05  85220 -0.005134
4015654  2016-06  85220 -0.000573
4015655  2016-07  85220  0.004016
4015656  2016-08  85220  0.003429
4015657  2016-09  85220  0.003417
4015658  2016-10  85220  0.006810
4015659  2016-11  85220  0.009019
4015660  2016-12  85220  0.007263
4015661  2017-01  85220  0.008319
4015662  2017-02  85220  0.008251
4015663  2017-03  85220  0.005456
4015664  2017-04  85220  0.000543
4015665  2017-05  85220  0.002711
4015666  2017-06  85220  0.008112
4015667  2017-07  85220  0.012339
4015668  2017-08  85220  0.011129
4015669  2017-09  85220  0.004193
4015670  2017-10  85220 -0.001044
4015671  2017-11  85220 -0.005225
4015672  2017-12  85220 -0.003676
4015673  2018-01  85220  0.002636

[4015674 rows x 3 columns]

In [71]:
from datetime import datetime
datestring = "2008-12"
dt = datetime.strptime(datestring, '%Y-%m')
print (dt.year, dt.month, dt.day)

2008 12 1

In [72]:
Zip_Zhvi_AllHomesT['index'] =  pd.to_datetime(Zip_Zhvi_AllHomesT['index'], format='%Y-%m')
Zip_Zhvi_AllHomesT

             index    zip     price
0       1996-04-01  10025       NaN
1       1996-05-01  10025       NaN
2       1996-06-01  10025       NaN
3       1996-07-01  10025       NaN
4       1996-08-01  10025       NaN
5       1996-09-01  10025       NaN
6       1996-10-01  10025       NaN
7       1996-11-01  10025       NaN
8       1996-12-01  10025       NaN
9       1997-01-01  10025       NaN
10      1997-02-01  10025       NaN
11      1997-03-01  10025       NaN
12      1997-04-01  10025       NaN
13      1997-05-01  10025       NaN
14      1997-06-01  10025       NaN
15      1997-07-01  10025       NaN
16      1997-08-01  10025       NaN
17      1997-09-01  10025       NaN
18      1997-10-01  10025       NaN
19      1997-11-01  10025       NaN
20      1997-12-01  10025       NaN
21      1998-01-01  10025       NaN
22      1998-02-01  10025       NaN
23      1998-03-01  10025       NaN
24      1998-04-01  10025       NaN
25      1998-05-01  10025       NaN
26      1998-06-01  10025       NaN
27      1998-07-01  10025       NaN
28      1998-08-01  10025       NaN
29      1998-09-01  10025       NaN
...            ...    ...       ...
4015644 2015-08-01  85220  0.008855
4015645 2015-09-01  85220  0.015214
4015646 2015-10-01  85220  0.017291
4015647 2015-11-01  85220  0.009632
4015648 2015-12-01  85220  0.006173
4015649 2016-01-01  85220  0.002231
4015650 2016-02-01  85220 -0.006678
4015651 2016-03-01  85220 -0.011204
4015652 2016-04-01  85220 -0.006799
4015653 2016-05-01  85220 -0.005134
4015654 2016-06-01  85220 -0.000573
4015655 2016-07-01  85220  0.004016
4015656 2016-08-01  85220  0.003429
4015657 2016-09-01  85220  0.003417
4015658 2016-10-01  85220  0.006810
4015659 2016-11-01  85220  0.009019
4015660 2016-12-01  85220  0.007263
4015661 2017-01-01  85220  0.008319
4015662 2017-02-01  85220  0.008251
4015663 2017-03-01  85220  0.005456
4015664 2017-04-01  85220  0.000543
4015665 2017-05-01  85220  0.002711
4015666 2017-06-01  85220  0.008112
4015667 2017-07-01  85220  0.012339
4015668 2017-08-01  85220  0.011129
4015669 2017-09-01  85220  0.004193
4015670 2017-10-01  85220 -0.001044
4015671 2017-11-01  85220 -0.005225
4015672 2017-12-01  85220 -0.003676
4015673 2018-01-01  85220  0.002636

[4015674 rows x 3 columns]

In [73]:
Zip_Zhvi_AllHomesT

             index    zip     price
0       1996-04-01  10025       NaN
1       1996-05-01  10025       NaN
2       1996-06-01  10025       NaN
3       1996-07-01  10025       NaN
4       1996-08-01  10025       NaN
5       1996-09-01  10025       NaN
6       1996-10-01  10025       NaN
7       1996-11-01  10025       NaN
8       1996-12-01  10025       NaN
9       1997-01-01  10025       NaN
10      1997-02-01  10025       NaN
11      1997-03-01  10025       NaN
12      1997-04-01  10025       NaN
13      1997-05-01  10025       NaN
14      1997-06-01  10025       NaN
15      1997-07-01  10025       NaN
16      1997-08-01  10025       NaN
17      1997-09-01  10025       NaN
18      1997-10-01  10025       NaN
19      1997-11-01  10025       NaN
20      1997-12-01  10025       NaN
21      1998-01-01  10025       NaN
22      1998-02-01  10025       NaN
23      1998-03-01  10025       NaN
24      1998-04-01  10025       NaN
25      1998-05-01  10025       NaN
26      1998-06-01  10025       NaN
27      1998-07-01  10025       NaN
28      1998-08-01  10025       NaN
29      1998-09-01  10025       NaN
...            ...    ...       ...
4015644 2015-08-01  85220  0.008855
4015645 2015-09-01  85220  0.015214
4015646 2015-10-01  85220  0.017291
4015647 2015-11-01  85220  0.009632
4015648 2015-12-01  85220  0.006173
4015649 2016-01-01  85220  0.002231
4015650 2016-02-01  85220 -0.006678
4015651 2016-03-01  85220 -0.011204
4015652 2016-04-01  85220 -0.006799
4015653 2016-05-01  85220 -0.005134
4015654 2016-06-01  85220 -0.000573
4015655 2016-07-01  85220  0.004016
4015656 2016-08-01  85220  0.003429
4015657 2016-09-01  85220  0.003417
4015658 2016-10-01  85220  0.006810
4015659 2016-11-01  85220  0.009019
4015660 2016-12-01  85220  0.007263
4015661 2017-01-01  85220  0.008319
4015662 2017-02-01  85220  0.008251
4015663 2017-03-01  85220  0.005456
4015664 2017-04-01  85220  0.000543
4015665 2017-05-01  85220  0.002711
4015666 2017-06-01  85220  0.008112
4015667 2017-07-01  85220  0.012339
4015668 2017-08-01  85220  0.011129
4015669 2017-09-01  85220  0.004193
4015670 2017-10-01  85220 -0.001044
4015671 2017-11-01  85220 -0.005225
4015672 2017-12-01  85220 -0.003676
4015673 2018-01-01  85220  0.002636

[4015674 rows x 3 columns]

In [59]:
AllRegionsForePublic = pd.read_csv('http://files.zillowstatic.com/research/public/AllRegionsForePublic.csv')

,Region,RegionName,State,ForecastYoYPctChange,MSAName,CountyName,CityName
0,National,United States,US,3.078073,NaN,NaN,NaN
1,MSA,"Akron, OH",OH,2.515573,"Akron, OH",NaN,NaN
2,MSA,"Albany, GA",GA,3.579034,"Albany, GA",NaN,NaN
3,MSA,"Albany, NY",NY,3.086973,"Albany, NY",NaN,NaN
4,MSA,"Albuquerque, NM",NM,2.859574,"Albuquerque, NM",NaN,NaN
5,MSA,"Alexandria, LA",LA,2.003955,"Alexandria, LA",NaN,NaN
6,MSA,"Allentown, PA",PA,1.976884,"Allentown, PA",NaN,NaN
7,MSA,"Altoona, PA",PA,1.364871,"Altoona, PA",NaN,NaN
8,MSA,"Amarillo, TX",TX,2.140482,"Amarillo, TX",NaN,NaN
9,MSA,"Ames, IA",IA,3.987445,"Ames, IA",NaN,NaN
10,MSA,"Anchorage, AK",AK,5.412158,"Anchorage, AK",NaN,NaN
11,MSA,"Ann Arbor, MI",MI,4.785821,"Ann Arbor, MI",NaN,NaN
12,MSA,"Appleton, WI",WI,3.520030,"Appleton, WI",NaN,NaN
13,MSA,"Asheville, NC",NC,2.270682,"Asheville, NC",NaN,NaN
14,MSA,"Athens, GA",GA,3.765132,"Athens, GA",NaN,NaN
15,MSA,"Atlanta, GA",GA,3.645099,"Atlanta, GA",NaN,NaN
16,MSA,"Atlantic City, NJ",NJ,3.167554,"Atlantic City, NJ",NaN,NaN
17,MSA,"Auburn, AL",AL,2.892657,"Auburn, AL",NaN,NaN
18,MSA,"Augusta, GA",GA,3.121328,"Augusta, GA",NaN,NaN
19,MSA,"Austin, TX",TX,1.914706,"Austin, TX",NaN,NaN
20,MSA,"Bakersfield, CA",CA,4.011702,"Bakersfield, CA",NaN,NaN
21,MSA,"Baltimore, MD",MD,1.623232,"Baltimore, MD",NaN,NaN
22,MSA,"Bangor, ME",ME,4.751449,"Bangor, ME",NaN,NaN
23,MSA,"Cape Cod, MA",MA,3.112330,"Cape Cod, MA",NaN,NaN
24,MSA,"Baton Rouge, LA",LA,2.990687,"Baton Rouge, LA",NaN,NaN
25,MSA,"Battle Creek, MI",MI,3.177922,"Battle Creek, MI",NaN,NaN
26,MSA,"Bay City, MI",MI,3.344374,"Bay City, MI",NaN,NaN
27,MSA,"Bellingham, WA",WA,2.997830,"Bellingham, WA",NaN,NaN
28,MSA,"Bend, OR",OR,1.088562,"Bend, OR",NaN,NaN
29,MSA,"Billings, MT",MT,3.832449,"Billings, MT",NaN,NaN
...,...,...,...,...,...,...,...
22368,ZipCode,97317,OR,6.251949,"Salem, OR",Marion,Four Corners
22369,ZipCode,60642,IL,1.623506,"Chicago, IL",Cook,Chicago
22370,ZipCode,61705,IL,3.067968,"Bloomington, IL",McLean,Bloomington
22371,ZipCode,81507,CO,0.644957,"Grand Junction, CO",Mesa,Grand Junction
22372,ZipCode,84081,UT,2.661701,"Salt Lake City, UT",Salt Lake,West Jordan
22373,ZipCode,85756,AZ,4.411510,"Tucson, AZ",Pima,Tucson
22374,ZipCode,86315,AZ,2.178622,"Prescott, AZ",Yavapai,Prescott Valley
22375,ZipCode,85118,AZ,1.153896,"Phoenix, AZ",Pinal,Gold Canyon
22376,ZipCode,85119,AZ,2.201336,"Phoenix, AZ",Pinal,Apache Junction
22377,ZipCode,85122,AZ,2.265596,"Phoenix, AZ",Pinal,Casa Grande
22378,ZipCode,85128,AZ,2.934060,"Phoenix, AZ",Pinal,Coolidge
22379,ZipCode,85131,AZ,5.141441,"Phoenix, AZ",Pinal,Eloy
22380,ZipCode,85132,AZ,2.250587,"Phoenix, AZ",Pinal,Florence
22381,ZipCode,85137,AZ,3.754152,"Phoenix, AZ",Pinal,Kearny
22382,ZipCode,85138,AZ,2.055506,"Phoenix, AZ",Pinal,Maricopa
22383,ZipCode,85139,AZ,2.090948,"Phoenix, AZ",Pinal,Maricopa
22384,ZipCode,85142,AZ,2.170574,"Phoenix, AZ",Maricopa,Queen Creek
22385,ZipCode,85145,AZ,4.031478,"Tucson, AZ",Pima,Marana
22386,ZipCode,85194,AZ,1.528291,"Phoenix, AZ",Pinal,Casa Grande
22387,ZipCode,50324,IA,3.915121,"Des Moines, IA",Polk,Windsor Heights
22388,ZipCode,60484,IL,2.701492,"Chicago, IL",Will,University Park
22389,ZipCode,19060,PA,1.452568,"Philadelphia, PA",Delaware,Garnet Valley
22390,ZipCode,85123,AZ,2.764789,"Phoenix, AZ",Pinal,Casa Grande
22391,ZipCode,60958,IL,3.020574,"Kankakee, IL",Kankakee,Hopkins Park
22392,ZipCode,93737,CA,5.642485,"Fresno, CA",Fresno,Fresno
22393,ZipCode,84129,UT,3.675739,"Salt Lake City, UT",Salt Lake,Taylorsville
22394,ZipCode,75033,TX,1.487044,"Dallas-Fort Worth, TX",Collin,Frisco
22395,ZipCode,84009,UT,3.921859,"Salt Lake City, UT",Salt Lake,South Jordan
22396,ZipCode,86005,AZ,0.806701,"Flagstaff, AZ",Coconino,Flagstaff
22397,ZipCode,97003,OR,4.681196,"Portland, OR",Washington,Beaverton

In [60]:
AllRegionsForePublic.head()

,Region,RegionName,State,ForecastYoYPctChange,MSAName,CountyName,CityName
0,National,United States,US,3.078073,NaN,NaN,NaN
1,MSA,"Akron, OH",OH,2.515573,"Akron, OH",NaN,NaN
2,MSA,"Albany, GA",GA,3.579034,"Albany, GA",NaN,NaN
3,MSA,"Albany, NY",NY,3.086973,"Albany, NY",NaN,NaN
4,MSA,"Albuquerque, NM",NM,2.859574,"Albuquerque, NM",NaN,NaN

In [183]:
coest2016alldata = pd.read_csv('https://www2.census.gov/programs-surveys/popest/datasets/2010-2016/counties/totals/co-est2016-alldata.csv',encoding = "ISO-8859-1")

In [184]:

 #.shape
coest2016alldata = coest2016alldata [coest2016alldata['COUNTY'] !=0]
coest2016alldata

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RDOMESTICMIG2016,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54742,...,-4.607582,2.149969,-2.799695,4.128528,6.163804,-5.295515,-4.571158,2.259290,-2.654256,4.255281
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183199,...,21.672935,19.038117,17.311339,19.628723,15.757654,18.612620,22.757100,20.248574,18.585398,20.807611
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27348,...,-7.027927,-4.208488,-16.593442,-9.495549,-1.280316,-7.418561,-7.360829,-4.506434,-16.819716,-9.686991
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-6.556506,0.088865,0.088747,1.504292,-4.956466,-4.318988,-5.980596,0.888652,0.887469,2.300681
5,50,3,6,1,9,Alabama,Blount County,57322,57324,57376,...,-1.627452,-2.791093,-1.405067,-1.126712,1.755255,-0.848639,-1.125366,-2.236341,-0.780593,-0.468019
6,50,3,6,1,11,Alabama,Bullock County,10914,10911,10892,...,-8.666981,10.992108,-26.456276,-9.703608,-20.634774,-6.923653,-7.819124,11.931605,-25.605896,-8.838930
7,50,3,6,1,13,Alabama,Butler County,20947,20946,20938,...,-15.221368,-0.393963,-7.424089,-6.330376,-4.929881,-7.467540,-14.879863,0.000000,-7.028137,-5.931612
8,50,3,6,1,15,Alabama,Calhoun County,118572,118586,118468,...,-5.537416,-4.459520,-3.954621,-4.019209,-6.341976,-4.494688,-5.314892,-4.252901,-3.703672,-3.784320
9,50,3,6,1,17,Alabama,Chambers County,34215,34170,34101,...,2.052575,-3.435165,1.440350,-4.566479,-1.585740,4.611544,2.551058,-2.877318,1.969459,-4.036178
10,50,3,6,1,19,Alabama,Cherokee County,25989,25986,25977,...,5.375209,-0.653620,-3.599768,5.286583,6.186359,1.382223,5.567181,-0.461379,-3.406232,5.480943
11,50,3,6,1,21,Alabama,Chilton County,43643,43631,43675,...,0.320139,0.136919,-3.398606,1.435897,-0.709114,-3.018833,0.388740,0.410757,-3.124893,1.732194
12,50,3,6,1,23,Alabama,Choctaw County,13859,13858,13840,...,-8.688226,-1.948003,-5.507148,-13.285485,-14.426230,-1.472808,-8.762485,-2.022927,-5.582588,-13.361839
13,50,3,6,1,25,Alabama,Clarke County,25833,25833,25762,...,-0.915368,-8.405548,-6.977495,-13.274156,-6.821149,-16.490128,-0.756174,-8.205416,-6.775833,-13.070565
14,50,3,6,1,27,Alabama,Clay County,13932,13932,13882,...,4.605385,4.598213,2.815023,3.186720,-10.523260,-13.413421,4.456825,4.524048,2.740944,3.112610
15,50,3,6,1,29,Alabama,Cleburne County,14972,14972,14975,...,7.276611,3.188627,-2.793296,-3.409091,-3.539114,-4.949171,7.209853,3.122197,-2.859803,-3.475936
16,50,3,6,1,31,Alabama,Coffee County,49948,49948,50183,...,-13.188237,-4.079380,2.101748,0.645231,2.721845,10.918319,-11.088324,-1.970715,4.498134,2.287636
17,50,3,6,1,33,Alabama,Colbert County,54428,54428,54521,...,1.303362,1.800097,0.036791,0.589802,0.715721,1.560306,1.542006,2.038886,0.275933,0.829409
18,50,3,6,1,35,Alabama,Conecuh County,13228,13228,13209,...,-7.652765,-15.851218,0.872393,-9.843150,0.227256,-12.366412,-7.575465,-15.694276,1.031010,-9.683099
19,50,3,6,1,37,Alabama,Coosa County,11539,11758,11758,...,-4.851970,-23.430350,-7.169126,-8.369381,-31.997233,-11.519716,-5.031673,-23.613399,-7.169126,-8.369381
20,50,3,6,1,39,Alabama,Covington County,37765,37765,37801,...,1.742988,-0.290678,-2.040925,-2.928686,6.933186,-4.110239,1.795806,-0.237828,-1.987913,-2.875438
21,50,3,6,1,41,Alabama,Crenshaw County,13906,13898,13857,...,-3.166151,3.168659,2.952402,4.678110,2.953890,2.587787,-2.518529,3.960824,3.744509,5.397819
22,50,3,6,1,43,Alabama,Cullman County,80406,80410,80476,...,4.171788,4.336063,7.140009,6.815596,-1.193043,-0.733794,4.494605,4.681960,7.495783,7.156375
23,50,3,6,1,45,Alabama,Dale County,50251,50247,50360,...,-15.512399,-12.930948,-5.346348,-5.558035,-9.574140,-1.473883,-13.733271,-11.377620,-3.179457,-4.624934
24,50,3,6,1,47,Alabama,Dallas County,43820,43820,43820,...,-17.804435,-9.846434,-15.116773,-19.604208,-15.512427,-12.843930,-17.922501,-9.966220,-15.213831,-19.678372
25,50,3,6,1,49,Alabama,DeKalb County,71109,71115,71143,...,-1.748412,-0.648668,0.000000,-2.114225,1.417226,-8.401826,-1.128008,0.155116,0.789049,-1.324914
26,50,3,6,1,51,Alabama,Elmore County,79303,79296,79573,...,0.646155,-1.957202,1.777427,3.471605,2.518750,-0.411674,1.354441,-1.201573,2.641454,4.109497
27,50,3,6,1,53,Alabama,Escambia County,38319,38319,38314,...,-5.082960,0.528018,0.184928,-2.250017,-2.978796,-3.434264,-5.056624,0.554419,0.237765,-2.197075
28,50,3,6,1,55,Alabama,Etowah County,104430,104427,104449,...,-2.144179,-2.288075,-2.366129,0.428355,-0.757122,2.254727,-1.913416,-2.027409,-2.104304,0.691209
29,50,3,6,1,57,Alabama,Fayette County,17241,17241,17231,...,-3.961684,0.356305,-3.338898,-5.891370,-5.073774,-0.411414,-4.020814,0.296921,-3.398521,-5.951486
30,50,3,6,1,59,Alabama,Franklin County,31704,31709,31734,...,-8.170116,-0.983425,-2.980248,1.044800,0.189072,-3.565456,-5.953418,1.554445,-0.253638,3.830932
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3162,50,2,3,55,129,Wisconsin,Washburn County,15911,15911,15930,...,-6.725888,4.015808,-5.438782,10.896039,-6.178677,7.838923,-6.281726,4.462009,-4.990882,11.344699
3163,50,2,3,55,131,Wisconsin,Washington County,131887,131887,131996,...,-2.214122,1.532256,-0.217027,1.104020,-0.423780,1.282927,-1.694481,2.148163,0.434054,1.745546
3164,50,2,3,55,133,Wisconsin,Waukesha County,389891,389936,390083,...,0.101682,0.765097,-0.942283,3.435107,0.120375,3.193282,1.309153,2.107818,0.452195,4.781468
3165,50,2,3,55,135,Wisconsin,Waupaca County,52410,52410,52425,...,7.267358,-0.996455,0.288370,-3.093043,2.978606,-1.494797,7.535809,-0.670691,0.634414,-2.745075
3166,50,2,3,55,137,Wisconsin,Waushara County,24496,24496,24507,...,-4.343995,-4.617605,-4.188525,4.522540,4.930123,-2.283012,-3.975165,-4.246547,-3.815290,4.895961
3167,50,2,3,55,139,Wisconsin,Winnebago County,166994,166994,167061,...,0.768590,-2.210961,-4.704273,-0.771835,0.878380,3.697869,1.424847,-1.444495,-3.908438,0.017676
3168,50,2,3,55,141,Wisconsin,Wood County,74749,74749,74785,...,-6.977152,-5.834227,-3.732919,-2.431777,-3.641890,-4.795358,-6.761225,-5.617139,-3.528562,-2.240514
3170,50,4,8,56,1,Wyoming,Albany County,36299,36299,36428,...,-2.506667,-4.822342,-4.267369,-6.654877,6.355441,5.871342,1.226667,-0.529928,0.131709,-2.358027
3171,50,4,8,56,3,Wyoming,Big Horn County,11668,11668,11673,...,15.404040,-7.957449,5.190674,-0.916819,4.527013,3.145857,15.656566,-7.538636,5.609276,-0.500083
3172,50,4,8,56,5,Wyoming,Campbell County,46133,46133,46246,...,-6.125766,-8.551532,12.134380,-20.787479,-2.757432,15.476468,-5.813227,-8.074141,12.646812,-20.298361
3173,50,4,8,56,7,Wyoming,Carbon County,15885,15885,15837,...,3.748412,-2.972050,-21.540324,0.128320,-6.885443,-12.950325,4.193139,-2.466169,-21.094223,0.577441
3174,50,4,8,56,9,Wyoming,Converse County,13833,13833,13827,...,18.737013,-18.482218,0.420595,-17.536476,-12.628370,17.071853,20.286690,-16.802016,2.243174,-15.712682
3175,50,4,8,56,11,Wyoming,Crook County,7083,7083,7115,...,0.838809,5.281078,18.701795,1.881973,0.000000,-4.618291,0.838809,5.281078,18.701795,1.881973
3176,50,4,8,56,13,Wyoming,Fremont County,40123,40123,40222,...,-5.308011,-13.930714,-11.772691,-4.690001,3.118156,7.855613,-5.137570,-13.685886,-11.451842,-4.367408
3177,50,4,8,56,15,Wyoming,Goshen County,13249,13247,13405,...,-8.087343,-2.214594,0.442184,-16.307168,14.816461,4.477393,-7.278609,-0.959657,1.768738,-15.047068
3178,50,4,8,56,17,Wyoming,Hot Springs County,4812,4812,4813,...,2.065476,-4.358203,-6.497590,-9.974533,5.398671,5.588905,2.065476,-4.358203,-6.497590,-9.974533
3179,50,4,8,56,19,Wyoming,Johnson County,8569,8569,8581,...,-0.812678,-9.196205,2.099248,-13.237275,4.880033,-3.828306,-0.464387,-8.614167,2.682372,-12.651555
3180,50,4,8,56,21,Wyoming,Laramie County,91738,91881,92272,...,4.928846,-2.539114,2.843156,4.689764,-1.168142,17.009743,6.313118,-1.373619,4.404307,5.590854
3181,50,4,8,56,23,Wyoming,Lincoln County,18106,18106,18090,...,13.345466,6.015119,2.892573,12.359046,-9.748532,-11.680294,13.786638,6.557022,3.428235,12.887211
3182,50,4,8,56,25,Wyoming,Natrona County,75450,75450,75474,...,25.085476,-2.116610,2.652439,-20.241377,7.479392,22.630506,25.461195,-1.710517,3.153591,-19.751271
3183,50,4,8,56,27,Wyoming,Niobrara County,2484,2484,2492,...,28.286853,-22.235458,5.212510,-12.457304,-0.401687,0.000000,28.286853,-22.235458,5.212510,-12.457304
3184,50,4,8,56,29,Wyoming,Park County,28205,28205,28258,...,5.419867,-3.851113,-4.301075,7.533086,6.627419,10.293989,6.835246,-2.372561,-2.787097,9.039703
3185,50,4,8,56,31,Wyoming,Platte County,8667,8667,8677,...,-0.917484,9.612084,3.640501,-15.441807,4.948216,5.160846,-1.032169,9.726513,3.754266,-15.327424
3186,50,4,8,56,33,Wyoming,Sheridan County,29116,29116,29146,...,4.380275,3.312643,0.732564,3.617117,2.498674,8.494012,5.424802,4.383397,1.898007,4.745391
3187,50,4,8,56,35,Wyoming,Sublette County,10247,10247,10243,...,-39.617486,-14.725636,-20.104544,-18.527945,-20.894644,16.148645,-39.519906,-14.626138,-19.903498,-18.324341
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43589,...,-5.408401,-12.362119,-13.695727,-20.009453,1.004371,16.069304,-5.297573,-12.228954,-13.472670,-19.784375
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,18.906083,13.904572,1.045319,-4.712087,0.374085,2.270516,20.314950,15.720137,3.179512,-2.637040
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-7.856582,-14.184397,-11.033821,-9.761493,-17.705854,-5.439580,-8.713663,-14.948540,-11.753418,-10.434699
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8544,...,-1.184904,-17.315500,2.644231,-11.467198,-11.872576,-2.129296,-1.658866,-17.793169,2.163462,-11.950027
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7182,...,12.229407,1.533956,6.107294,2.212084,-12.452777,-7.617973,12.791678,1.952308,6.662503,2.765104

In [185]:
states = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'
}

In [186]:
states
states = dict (zip(states.values(),states.keys()))

states

{'Alabama': 'AL',
 'Alaska': 'AK',
 'American Samoa': 'AS',
 'Arizona': 'AZ',
 'Arkansas': 'AR',
 'California': 'CA',
 'Colorado': 'CO',
 'Connecticut': 'CT',
 'Delaware': 'DE',
 'District of Columbia': 'DC',
 'Florida': 'FL',
 'Georgia': 'GA',
 'Guam': 'GU',
 'Hawaii': 'HI',
 'Idaho': 'ID',
 'Illinois': 'IL',
 'Indiana': 'IN',
 'Iowa': 'IA',
 'Kansas': 'KS',
 'Kentucky': 'KY',
 'Louisiana': 'LA',
 'Maine': 'ME',
 'Maryland': 'MD',
 'Massachusetts': 'MA',
 'Michigan': 'MI',
 'Minnesota': 'MN',
 'Mississippi': 'MS',
 'Missouri': 'MO',
 'Montana': 'MT',
 'National': 'NA',
 'Nebraska': 'NE',
 'Nevada': 'NV',
 'New Hampshire': 'NH',
 'New Jersey': 'NJ',
 'New Mexico': 'NM',
 'New York': 'NY',
 'North Carolina': 'NC',
 'North Dakota': 'ND',
 'Northern Mariana Islands': 'MP',
 'Ohio': 'OH',
 'Oklahoma': 'OK',
 'Oregon': 'OR',
 'Pennsylvania': 'PA',
 'Puerto Rico': 'PR',
 'Rhode Island': 'RI',
 'South Carolina': 'SC',
 'South Dakota': 'SD',
 'Tennessee': 'TN',
 'Texas': 'TX',
 'Utah': 'UT',
 'Vermont': 'VT',
 'Virgin Islands': 'VI',
 'Virginia': 'VA',
 'Washington': 'WA',
 'West Virginia': 'WV',
 'Wisconsin': 'WI',
 'Wyoming': 'WY'}

In [187]:
#coest2016alldata = 
coest2016alldata = coest2016alldata.replace({"STNAME": states})
#coest2016alldata

In [188]:
coest2016alldata['CTYNAME'] = coest2016alldata['CTYNAME'] + ' '+ coest2016alldata['STNAME']

#coest2016alldata.set_index('STNAME', inplace=True)
coest2016alldata['CTYNAME'] = coest2016alldata['CTYNAME'].str.replace('County','')
coest2016alldata.head() #.columns[67:77]

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RDOMESTICMIG2016,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016
1,50,3,6,1,1,AL,Autauga AL,54571,54571,54742,...,-4.607582,2.149969,-2.799695,4.128528,6.163804,-5.295515,-4.571158,2.259290,-2.654256,4.255281
2,50,3,6,1,3,AL,Baldwin AL,182265,182265,183199,...,21.672935,19.038117,17.311339,19.628723,15.757654,18.612620,22.757100,20.248574,18.585398,20.807611
3,50,3,6,1,5,AL,Barbour AL,27457,27457,27348,...,-7.027927,-4.208488,-16.593442,-9.495549,-1.280316,-7.418561,-7.360829,-4.506434,-16.819716,-9.686991
4,50,3,6,1,7,AL,Bibb AL,22915,22919,22861,...,-6.556506,0.088865,0.088747,1.504292,-4.956466,-4.318988,-5.980596,0.888652,0.887469,2.300681
5,50,3,6,1,9,AL,Blount AL,57322,57324,57376,...,-1.627452,-2.791093,-1.405067,-1.126712,1.755255,-0.848639,-1.125366,-2.236341,-0.780593,-0.468019

In [189]:
listofcols = coest2016alldata.columns #[67:77]
listofcols[77:87]

Index(['GQESTIMATES2014', 'GQESTIMATES2015', 'GQESTIMATES2016', 'RBIRTH2011',
       'RBIRTH2012', 'RBIRTH2013', 'RBIRTH2014', 'RBIRTH2015', 'RBIRTH2016',
       'RDEATH2011'],
      dtype='object')

In [190]:

coest2016alldata.set_index('CTYNAME', inplace=True)
coest2016alldata

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RDOMESTICMIG2016,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016
CTYNAME,,,,,,,,,,,,,,,,,,,,,
Autauga AL,50,3,6,1,1,AL,54571,54571,54742,55255,...,-4.607582,2.149969,-2.799695,4.128528,6.163804,-5.295515,-4.571158,2.259290,-2.654256,4.255281
Baldwin AL,50,3,6,1,3,AL,182265,182265,183199,186653,...,21.672935,19.038117,17.311339,19.628723,15.757654,18.612620,22.757100,20.248574,18.585398,20.807611
Barbour AL,50,3,6,1,5,AL,27457,27457,27348,27326,...,-7.027927,-4.208488,-16.593442,-9.495549,-1.280316,-7.418561,-7.360829,-4.506434,-16.819716,-9.686991
Bibb AL,50,3,6,1,7,AL,22915,22919,22861,22736,...,-6.556506,0.088865,0.088747,1.504292,-4.956466,-4.318988,-5.980596,0.888652,0.887469,2.300681
Blount AL,50,3,6,1,9,AL,57322,57324,57376,57707,...,-1.627452,-2.791093,-1.405067,-1.126712,1.755255,-0.848639,-1.125366,-2.236341,-0.780593,-0.468019
Bullock AL,50,3,6,1,11,AL,10914,10911,10892,10722,...,-8.666981,10.992108,-26.456276,-9.703608,-20.634774,-6.923653,-7.819124,11.931605,-25.605896,-8.838930
Butler AL,50,3,6,1,13,AL,20947,20946,20938,20848,...,-15.221368,-0.393963,-7.424089,-6.330376,-4.929881,-7.467540,-14.879863,0.000000,-7.028137,-5.931612
Calhoun AL,50,3,6,1,15,AL,118572,118586,118468,117736,...,-5.537416,-4.459520,-3.954621,-4.019209,-6.341976,-4.494688,-5.314892,-4.252901,-3.703672,-3.784320
Chambers AL,50,3,6,1,17,AL,34215,34170,34101,34006,...,2.052575,-3.435165,1.440350,-4.566479,-1.585740,4.611544,2.551058,-2.877318,1.969459,-4.036178
Cherokee AL,50,3,6,1,19,AL,25989,25986,25977,26073,...,5.375209,-0.653620,-3.599768,5.286583,6.186359,1.382223,5.567181,-0.461379,-3.406232,5.480943
Chilton AL,50,3,6,1,21,AL,43643,43631,43675,43758,...,0.320139,0.136919,-3.398606,1.435897,-0.709114,-3.018833,0.388740,0.410757,-3.124893,1.732194
Choctaw AL,50,3,6,1,23,AL,13859,13858,13840,13610,...,-8.688226,-1.948003,-5.507148,-13.285485,-14.426230,-1.472808,-8.762485,-2.022927,-5.582588,-13.361839
Clarke AL,50,3,6,1,25,AL,25833,25833,25762,25549,...,-0.915368,-8.405548,-6.977495,-13.274156,-6.821149,-16.490128,-0.756174,-8.205416,-6.775833,-13.070565
Clay AL,50,3,6,1,27,AL,13932,13932,13882,13676,...,4.605385,4.598213,2.815023,3.186720,-10.523260,-13.413421,4.456825,4.524048,2.740944,3.112610
Cleburne AL,50,3,6,1,29,AL,14972,14972,14975,14976,...,7.276611,3.188627,-2.793296,-3.409091,-3.539114,-4.949171,7.209853,3.122197,-2.859803,-3.475936
Coffee AL,50,3,6,1,31,AL,49948,49948,50183,50484,...,-13.188237,-4.079380,2.101748,0.645231,2.721845,10.918319,-11.088324,-1.970715,4.498134,2.287636
Colbert AL,50,3,6,1,33,AL,54428,54428,54521,54460,...,1.303362,1.800097,0.036791,0.589802,0.715721,1.560306,1.542006,2.038886,0.275933,0.829409
Conecuh AL,50,3,6,1,35,AL,13228,13228,13209,13193,...,-7.652765,-15.851218,0.872393,-9.843150,0.227256,-12.366412,-7.575465,-15.694276,1.031010,-9.683099
Coosa AL,50,3,6,1,37,AL,11539,11758,11758,11369,...,-4.851970,-23.430350,-7.169126,-8.369381,-31.997233,-11.519716,-5.031673,-23.613399,-7.169126,-8.369381
Covington AL,50,3,6,1,39,AL,37765,37765,37801,38066,...,1.742988,-0.290678,-2.040925,-2.928686,6.933186,-4.110239,1.795806,-0.237828,-1.987913,-2.875438
Crenshaw AL,50,3,6,1,41,AL,13906,13898,13857,13903,...,-3.166151,3.168659,2.952402,4.678110,2.953890,2.587787,-2.518529,3.960824,3.744509,5.397819
Cullman AL,50,3,6,1,43,AL,80406,80410,80476,80457,...,4.171788,4.336063,7.140009,6.815596,-1.193043,-0.733794,4.494605,4.681960,7.495783,7.156375
Dale AL,50,3,6,1,45,AL,50251,50247,50360,50119,...,-15.512399,-12.930948,-5.346348,-5.558035,-9.574140,-1.473883,-13.733271,-11.377620,-3.179457,-4.624934
Dallas AL,50,3,6,1,47,AL,43820,43820,43820,43207,...,-17.804435,-9.846434,-15.116773,-19.604208,-15.512427,-12.843930,-17.922501,-9.966220,-15.213831,-19.678372
DeKalb AL,50,3,6,1,49,AL,71109,71115,71143,71389,...,-1.748412,-0.648668,0.000000,-2.114225,1.417226,-8.401826,-1.128008,0.155116,0.789049,-1.324914
Elmore AL,50,3,6,1,51,AL,79303,79296,79573,80030,...,0.646155,-1.957202,1.777427,3.471605,2.518750,-0.411674,1.354441,-1.201573,2.641454,4.109497
Escambia AL,50,3,6,1,53,AL,38319,38319,38314,38227,...,-5.082960,0.528018,0.184928,-2.250017,-2.978796,-3.434264,-5.056624,0.554419,0.237765,-2.197075
Etowah AL,50,3,6,1,55,AL,104430,104427,104449,104236,...,-2.144179,-2.288075,-2.366129,0.428355,-0.757122,2.254727,-1.913416,-2.027409,-2.104304,0.691209
Fayette AL,50,3,6,1,57,AL,17241,17241,17231,17063,...,-3.961684,0.356305,-3.338898,-5.891370,-5.073774,-0.411414,-4.020814,0.296921,-3.398521,-5.951486
Franklin AL,50,3,6,1,59,AL,31704,31709,31734,31734,...,-8.170116,-0.983425,-2.980248,1.044800,0.189072,-3.565456,-5.953418,1.554445,-0.253638,3.830932
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Washburn WI,50,2,3,55,129,WI,15911,15911,15930,15792,...,-6.725888,4.015808,-5.438782,10.896039,-6.178677,7.838923,-6.281726,4.462009,-4.990882,11.344699
Washington WI,50,2,3,55,131,WI,131887,131887,131996,132292,...,-2.214122,1.532256,-0.217027,1.104020,-0.423780,1.282927,-1.694481,2.148163,0.434054,1.745546
Waukesha WI,50,2,3,55,133,WI,389891,389936,390083,390811,...,0.101682,0.765097,-0.942283,3.435107,0.120375,3.193282,1.309153,2.107818,0.452195,4.781468
Waupaca WI,50,2,3,55,135,WI,52410,52410,52425,52322,...,7.267358,-0.996455,0.288370,-3.093043,2.978606,-1.494797,7.535809,-0.670691,0.634414,-2.745075
Waushara WI,50,2,3,55,137,WI,24496,24496,24507,24579,...,-4.343995,-4.617605,-4.188525,4.522540,4.930123,-2.283012,-3.975165,-4.246547,-3.815290,4.895961
Winnebago WI,50,2,3,55,139,WI,166994,166994,167061,167646,...,0.768590,-2.210961,-4.704273,-0.771835,0.878380,3.697869,1.424847,-1.444495,-3.908438,0.017676
Wood WI,50,2,3,55,141,WI,74749,74749,74785,74588,...,-6.977152,-5.834227,-3.732919,-2.431777,-3.641890,-4.795358,-6.761225,-5.617139,-3.528562,-2.240514
Albany WY,50,4,8,56,1,WY,36299,36299,36428,36895,...,-2.506667,-4.822342,-4.267369,-6.654877,6.355441,5.871342,1.226667,-0.529928,0.131709,-2.358027
Big Horn WY,50,4,8,56,3,WY,11668,11668,11673,11742,...,15.404040,-7.957449,5.190674,-0.916819,4.527013,3.145857,15.656566,-7.538636,5.609276,-0.500083
Campbell WY,50,4,8,56,5,WY,46133,46133,46246,46594,...,-6.125766,-8.551532,12.134380,-20.787479,-2.757432,15.476468,-5.813227,-8.074141,12.646812,-20.298361
Carbon WY,50,4,8,56,7,WY,15885,15885,15837,15824,...,3.748412,-2.972050,-21.540324,0.128320,-6.885443,-12.950325,4.193139,-2.466169,-21.094223,0.577441
Converse WY,50,4,8,56,9,WY,13833,13833,13827,13730,...,18.737013,-18.482218,0.420595,-17.536476,-12.628370,17.071853,20.286690,-16.802016,2.243174,-15.712682
Crook WY,50,4,8,56,11,WY,7083,7083,7115,7139,...,0.838809,5.281078,18.701795,1.881973,0.000000,-4.618291,0.838809,5.281078,18.701795,1.881973
Fremont WY,50,4,8,56,13,WY,40123,40123,40222,40595,...,-5.308011,-13.930714,-11.772691,-4.690001,3.118156,7.855613,-5.137570,-13.685886,-11.451842,-4.367408
Goshen WY,50,4,8,56,15,WY,13249,13247,13405,13592,...,-8.087343,-2.214594,0.442184,-16.307168,14.816461,4.477393,-7.278609,-0.959657,1.768738,-15.047068
Hot Springs WY,50,4,8,56,17,WY,4812,4812,4813,4819,...,2.065476,-4.358203,-6.497590,-9.974533,5.398671,5.588905,2.065476,-4.358203,-6.497590,-9.974533
Johnson WY,50,4,8,56,19,WY,8569,8569,8581,8632,...,-0.812678,-9.196205,2.099248,-13.237275,4.880033,-3.828306,-0.464387,-8.614167,2.682372,-12.651555
Laramie WY,50,4,8,56,21,WY,91738,91881,92272,92637,...,4.928846,-2.539114,2.843156,4.689764,-1.168142,17.009743,6.313118,-1.373619,4.404307,5.590854
Lincoln WY,50,4,8,56,23,WY,18106,18106,18090,18018,...,13.345466,6.015119,2.892573,12.359046,-9.748532,-11.680294,13.786638,6.557022,3.428235,12.887211
Natrona WY,50,4,8,56,25,WY,75450,75450,75474,76410,...,25.085476,-2.116610,2.652439,-20.241377,7.479392,22.630506,25.461195,-1.710517,3.153591,-19.751271
Niobrara WY,50,4,8,56,27,WY,2484,2484,2492,2487,...,28.286853,-22.235458,5.212510,-12.457304,-0.401687,0.000000,28.286853,-22.235458,5.212510,-12.457304
Park WY,50,4,8,56,29,WY,28205,28205,28258,28476,...,5.419867,-3.851113,-4.301075,7.533086,6.627419,10.293989,6.835246,-2.372561,-2.787097,9.039703
Platte WY,50,4,8,56,31,WY,8667,8667,8677,8703,...,-0.917484,9.612084,3.640501,-15.441807,4.948216,5.160846,-1.032169,9.726513,3.754266,-15.327424
Sheridan WY,50,4,8,56,33,WY,29116,29116,29146,29285,...,4.380275,3.312643,0.732564,3.617117,2.498674,8.494012,5.424802,4.383397,1.898007,4.745391
Sublette WY,50,4,8,56,35,WY,10247,10247,10243,10145,...,-39.617486,-14.725636,-20.104544,-18.527945,-20.894644,16.148645,-39.519906,-14.626138,-19.903498,-18.324341
Sweetwater WY,50,4,8,56,37,WY,43806,43806,43589,44028,...,-5.408401,-12.362119,-13.695727,-20.009453,1.004371,16.069304,-5.297573,-12.228954,-13.472670,-19.784375
Teton WY,50,4,8,56,39,WY,21294,21294,21297,21474,...,18.906083,13.904572,1.045319,-4.712087,0.374085,2.270516,20.314950,15.720137,3.179512,-2.637040
Uinta WY,50,4,8,56,41,WY,21118,21118,21102,20918,...,-7.856582,-14.184397,-11.033821,-9.761493,-17.705854,-5.439580,-8.713663,-14.948540,-11.753418,-10.434699
Washakie WY,50,4,8,56,43,WY,8533,8533,8544,8470,...,-1.184904,-17.315500,2.644231,-11.467198,-11.872576,-2.129296,-1.658866,-17.793169,2.163462,-11.950027
Weston WY,50,4,8,56,45,WY,7208,7208,7182,7112,...,12.229407,1.533956,6.107294,2.212084,-12.452777,-7.617973,12.791678,1.952308,6.662503,2.765104

In [191]:
lofc = []
for colname in listofcols:
    lofc.append( colname[:-4])
    #print(colname)

lofc = list(set(lofc))
lofc

['NATURALINC',
 'ST',
 'DEATHS',
 'CENSUS201',
 'RINTERNATIONALMIG',
 'RDEATH',
 'BIRTHS',
 'SU',
 'RNATURALINC',
 'RDOMESTICMIG',
 'RESIDUAL',
 'INTERNATIONALMIG',
 'CO',
 'POPESTIMATE',
 'GQESTIMATESBASE',
 'GQESTIMATES',
 'RE',
 'S',
 'DOMESTICMIG',
 'ESTIMATESBASE',
 'NETMIG',
 'CTY',
 'RNETMIG',
 'NPOPCHG_',
 'RBIRTH',
 'DIVI']

In [181]:
#coest2016alldata = pd.read_csv()

#coest2016alldata.filter(regex='2010').columns

lofc = []
for colname in coest2016alldata.filter(regex='2010').columns:
    lofc.append( colname.replace('2010', ''))
    #print(colname)

lofc = list(set(lofc))
lofc

['GQESTIMATESBASE',
 'DOMESTICMIG',
 'GQESTIMATES',
 'BIRTHS',
 'ESTIMATESBASE',
 'DEATHS',
 'NATURALINC',
 'NPOPCHG_',
 'CENSUSPOP',
 'RESIDUAL',
 'INTERNATIONALMIG',
 'POPESTIMATE',
 'NETMIG']

In [204]:
#http://rstudio-pubs-static.s3.amazonaws.com/217450_4fabdb443de345efbc493cf0161ac51d.html

coest2016alldata.filter( like = 'DEATHS' ) #.max()

,DEATHS2010,DEATHS2011,DEATHS2012,DEATHS2013,DEATHS2014,DEATHS2015,DEATHS2016
CTYNAME,,,,,,,
Autauga AL,154,507,560,582,575,475,494
Baldwin AL,532,1825,1882,1903,1989,2080,2113
Barbour AL,128,318,293,295,313,319,314
Bibb AL,34,277,239,281,250,207,237
Blount AL,132,568,593,584,587,634,622
Bullock AL,52,132,117,120,115,108,111
Butler AL,60,261,272,261,288,268,241
Calhoun AL,313,1326,1357,1411,1392,1427,1441
Chambers AL,80,441,475,452,454,465,476
Cherokee AL,110,310,334,340,347,329,331
Chilton AL,142,474,495,499,485,442,483
Choctaw AL,21,160,145,194,177,171,170
Clarke AL,46,299,286,291,296,293,313
Clay AL,39,211,183,172,171,197,202
Cleburne AL,22,174,159,187,190,205,202
Coffee AL,77,508,492,519,467,528,537
Colbert AL,129,671,668,723,715,700,661
Conecuh AL,13,189,170,192,171,152,191
Coosa AL,11,163,140,133,122,109,101
Covington AL,92,489,479,518,492,542,520
Crenshaw AL,24,164,167,162,179,194,193
Cullman AL,227,910,965,961,946,973,1009
Dale AL,74,470,451,492,461,533,542
Dallas AL,76,544,504,555,537,514,545
DeKalb AL,151,783,710,782,723,774,771
Elmore AL,189,709,662,752,742,792,794
Escambia AL,63,440,480,447,467,467,458
Etowah AL,288,1356,1408,1346,1382,1413,1497
Fayette AL,39,256,255,237,218,220,234
Franklin AL,66,418,380,409,406,370,378
...,...,...,...,...,...,...,...
Washburn WI,22,217,220,237,200,185,200
Washington WI,251,1018,1036,1038,1052,1111,1100
Waukesha WI,775,3059,3100,3182,3273,3258,3351
Waupaca WI,160,761,731,662,666,740,731
Waushara WI,45,269,281,278,245,274,252
Winnebago WI,363,1447,1427,1426,1403,1418,1449
Wood WI,163,739,752,778,685,857,749
Albany WY,31,189,192,188,198,182,183
Big Horn WY,50,131,127,136,144,123,121
Campbell WY,83,240,239,223,249,289,333
Carbon WY,17,114,125,118,160,129,138
Converse WY,39,99,132,127,118,105,112
Crook WY,20,64,54,76,56,54,66
Fremont WY,147,381,409,464,397,446,481
Goshen WY,23,143,131,141,141,140,138
Hot Springs WY,19,72,57,65,76,59,69
Johnson WY,9,86,79,93,85,76,76
Laramie WY,234,770,719,748,722,809,850
Lincoln WY,45,130,117,100,116,134,121
Natrona WY,186,665,657,715,702,716,729
Niobrara WY,3,21,29,29,25,23,21
Park WY,86,261,262,268,259,262,260
Platte WY,34,104,105,101,95,74,82
Sheridan WY,84,298,286,292,296,327,334
Sublette WY,3,53,38,48,57,49,58
Sweetwater WY,76,251,272,296,265,265,275
Teton WY,10,87,61,97,79,79,87
Uinta WY,49,139,115,136,148,121,134
Washakie WY,34,79,105,77,73,92,93
Weston WY,9,71,67,77,75,71,77

In [195]:
#coest2016alldata.head()
#coest2016alldata [coest2016alldata.filter( like = 'INTERNATIONALMIG' ) ['INTERNATIONALMIG2016']  ==   42607.000000]

#.max()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RDOMESTICMIG2016,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,RNETMIG2016
CTYNAME,,,,,,,,,,,,,,,,,,,,,
Los Angeles CA,50,4,9,6,37,CA,9818605,9818700,9825473,9888476,...,-4.337325,-5.81594,-6.158125,-7.423938,-0.801869,-0.508718,-0.727628,-1.699926,-1.853127,-3.215874

In [155]:
Zip_Zhvi_AllHomes_county = pd.read_csv('County_MedianListingPricePerSqft_AllHomes.csv')
Zip_Zhvi_AllHomes_county.dropna(thresh=40,inplace= True)

In [52]:
Zip_Zhvi_AllHomes_county["RegionName"] = Zip_Zhvi_AllHomes_county["RegionName"] + ' '+ Zip_Zhvi_AllHomes_county["State"]
Zip_Zhvi_AllHomes_county.head()

,RegionName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,SizeRank,2010-01,2010-02,2010-03,2010-04,...,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02
0,Los Angeles CA,CA,Los Angeles-Long Beach-Anaheim,6,37,1,NaN,NaN,NaN,NaN,...,405.932534,402.974504,403.773585,405.644758,405.762194,407.894737,409.179047,407.014682,408.113217,415.533981
1,Cook IL,IL,Chicago,17,31,2,174.785276,176.430518,177.547708,176.653797,...,179.548241,181.391011,180.735325,177.743590,176.880917,176.282524,173.878706,170.024269,170.359848,176.878931
2,Harris TX,TX,Houston,48,201,3,75.057737,76.010822,76.198630,76.419214,...,113.324176,113.091954,112.330199,112.718031,113.858962,114.239366,114.677334,115.560658,116.061141,116.717194
3,Maricopa AZ,AZ,Phoenix,4,13,4,NaN,NaN,NaN,NaN,...,150.517404,149.749024,148.996413,149.840836,151.248389,153.272577,154.105839,155.209831,156.574911,157.921212
4,San Diego CA,CA,San Diego,6,73,5,NaN,NaN,NaN,NaN,...,349.880383,348.833347,350.584400,352.425835,353.726974,353.903457,354.166667,356.666667,360.478334,366.177764

In [83]:
Zip_Zhvi_AllHomes_countyT= Zip_Zhvi_AllHomes_county.transpose()

Zip_Zhvi_AllHomes_countyT.drop(Zip_Zhvi_AllHomes_countyT.index[1:6], inplace= True)
Zip_Zhvi_AllHomes_countyT.columns = Zip_Zhvi_AllHomes_countyT.iloc[0]
Zip_Zhvi_AllHomes_countyT.drop(Zip_Zhvi_AllHomes_countyT.index[0], inplace= True)


#Zip_Zhvi_AllHomes_countyT = Zip_Zhvi_AllHomes_countyT.reset_index()
Zip_Zhvi_AllHomes_countyT.index =  pd.to_datetime(Zip_Zhvi_AllHomes_countyT.index, format='%Y-%m')
Zip_Zhvi_AllHomes_countyT['month'] = pd.DatetimeIndex(Zip_Zhvi_AllHomes_countyT.index).month

Zip_Zhvi_AllHomes_countyT = Zip_Zhvi_AllHomes_countyT.loc[Zip_Zhvi_AllHomes_countyT['month'] == 1]
Zip_Zhvi_AllHomes_countyT = Zip_Zhvi_AllHomes_countyT.pct_change()

del Zip_Zhvi_AllHomes_countyT['month']
# #>>> pd.melt(df, id_vars=['A'], value_vars=['B', 'C'])
Zip_Zhvi_AllHomes_countyT

RegionName,Los Angeles CA,Cook IL,Harris TX,Maricopa AZ,San Diego CA,Orange CA,Kings NY,Miami-Dade FL,Dallas TX,Queens NY,...,Granite MT,Hinsdale CO,Arecibo PR,Bayamon PR,Fajardo PR,Carolina PR,Guaynabo PR,Cabo Rojo PR,Saint Thomas VI,Trujillo Alto PR
2010-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2011-01-01,NaN,-0.198175,-0.019901,NaN,NaN,NaN,NaN,NaN,-0.097389,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2012-01-01,NaN,-0.121709,-0.032121,NaN,NaN,NaN,NaN,NaN,-0.093842,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2013-01-01,NaN,-0.008284,0.070297,NaN,NaN,NaN,NaN,NaN,0.182095,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.032336,NaN,NaN,NaN
2014-01-01,NaN,0.050950,0.126779,NaN,NaN,NaN,0.047424,0.155126,0.089532,0.077726,...,NaN,NaN,NaN,-0.200425,NaN,NaN,-0.036754,NaN,NaN,NaN
2015-01-01,0.050866,0.056545,0.188205,0.045540,0.046261,0.031704,0.302392,0.114909,0.116906,0.111958,...,-0.064464,NaN,NaN,0.066313,NaN,NaN,-0.192606,-0.118235,0.158508,NaN
2016-01-01,0.125296,0.103263,0.091277,0.088822,0.099379,0.062612,0.260484,0.264345,0.128639,0.177678,...,0.125000,0.015933,-0.045469,-0.078664,-0.247870,0.088261,-0.014925,-0.076569,0.031599,-0.020392
2017-01-01,0.071194,0.053197,-0.004711,0.051931,0.049536,0.051688,0.087515,0.082048,0.204854,0.082660,...,0.236667,0.032040,0.000479,0.027305,0.077535,-0.074221,-0.043298,-0.031273,0.108883,-0.091399
2018-01-01,0.061963,0.081679,0.047325,0.063000,0.080634,0.058822,0.057922,0.040303,0.090987,0.122523,...,-0.143547,0.058098,-0.092838,-0.094480,-0.262569,-0.134461,-0.067009,-0.030526,0.000107,0.028249

In [84]:
Zip_Zhvi_AllHomes_countyT = Zip_Zhvi_AllHomes_countyT.reset_index()

Zip_Zhvi_AllHomes_countyT = pd.melt(Zip_Zhvi_AllHomes_countyT,  id_vars='index', var_name='county', value_name='price')
Zip_Zhvi_AllHomes_countyT

           index            county     price
0     2010-01-01    Los Angeles CA       NaN
1     2011-01-01    Los Angeles CA       NaN
2     2012-01-01    Los Angeles CA       NaN
3     2013-01-01    Los Angeles CA       NaN
4     2014-01-01    Los Angeles CA       NaN
5     2015-01-01    Los Angeles CA  0.050866
6     2016-01-01    Los Angeles CA  0.125296
7     2017-01-01    Los Angeles CA  0.071194
8     2018-01-01    Los Angeles CA  0.061963
9     2010-01-01           Cook IL       NaN
10    2011-01-01           Cook IL -0.198175
11    2012-01-01           Cook IL -0.121709
12    2013-01-01           Cook IL -0.008284
13    2014-01-01           Cook IL  0.050950
14    2015-01-01           Cook IL  0.056545
15    2016-01-01           Cook IL  0.103263
16    2017-01-01           Cook IL  0.053197
17    2018-01-01           Cook IL  0.081679
18    2010-01-01         Harris TX       NaN
19    2011-01-01         Harris TX -0.019901
20    2012-01-01         Harris TX -0.032121
21    2013-01-01         Harris TX  0.070297
22    2014-01-01         Harris TX  0.126779
23    2015-01-01         Harris TX  0.188205
24    2016-01-01         Harris TX  0.091277
25    2017-01-01         Harris TX -0.004711
26    2018-01-01         Harris TX  0.047325
27    2010-01-01       Maricopa AZ       NaN
28    2011-01-01       Maricopa AZ       NaN
29    2012-01-01       Maricopa AZ       NaN
...          ...               ...       ...
17952 2016-01-01       Guaynabo PR -0.014925
17953 2017-01-01       Guaynabo PR -0.043298
17954 2018-01-01       Guaynabo PR -0.067009
17955 2010-01-01      Cabo Rojo PR       NaN
17956 2011-01-01      Cabo Rojo PR       NaN
17957 2012-01-01      Cabo Rojo PR       NaN
17958 2013-01-01      Cabo Rojo PR       NaN
17959 2014-01-01      Cabo Rojo PR       NaN
17960 2015-01-01      Cabo Rojo PR -0.118235
17961 2016-01-01      Cabo Rojo PR -0.076569
17962 2017-01-01      Cabo Rojo PR -0.031273
17963 2018-01-01      Cabo Rojo PR -0.030526
17964 2010-01-01   Saint Thomas VI       NaN
17965 2011-01-01   Saint Thomas VI       NaN
17966 2012-01-01   Saint Thomas VI       NaN
17967 2013-01-01   Saint Thomas VI       NaN
17968 2014-01-01   Saint Thomas VI       NaN
17969 2015-01-01   Saint Thomas VI  0.158508
17970 2016-01-01   Saint Thomas VI  0.031599
17971 2017-01-01   Saint Thomas VI  0.108883
17972 2018-01-01   Saint Thomas VI  0.000107
17973 2010-01-01  Trujillo Alto PR       NaN
17974 2011-01-01  Trujillo Alto PR       NaN
17975 2012-01-01  Trujillo Alto PR       NaN
17976 2013-01-01  Trujillo Alto PR       NaN
17977 2014-01-01  Trujillo Alto PR       NaN
17978 2015-01-01  Trujillo Alto PR       NaN
17979 2016-01-01  Trujillo Alto PR -0.020392
17980 2017-01-01  Trujillo Alto PR -0.091399
17981 2018-01-01  Trujillo Alto PR  0.028249

[17982 rows x 3 columns]

In [81]:
#Zip_Zhvi_AllHomes_countyT['index'] =  pd.to_datetime(Zip_Zhvi_AllHomes_countyT['index'], format='%Y-%m')
Zip_Zhvi_AllHomes_countyT

           index            county     price
0     2010-01-01    Los Angeles CA       NaN
1     2011-01-01    Los Angeles CA       NaN
2     2012-01-01    Los Angeles CA       NaN
3     2013-01-01    Los Angeles CA       NaN
4     2014-01-01    Los Angeles CA       NaN
5     2015-01-01    Los Angeles CA  0.050866
6     2016-01-01    Los Angeles CA  0.125296
7     2017-01-01    Los Angeles CA  0.071194
8     2018-01-01    Los Angeles CA  0.061963
9     2010-01-01           Cook IL       NaN
10    2011-01-01           Cook IL -0.198175
11    2012-01-01           Cook IL -0.121709
12    2013-01-01           Cook IL -0.008284
13    2014-01-01           Cook IL  0.050950
14    2015-01-01           Cook IL  0.056545
15    2016-01-01           Cook IL  0.103263
16    2017-01-01           Cook IL  0.053197
17    2018-01-01           Cook IL  0.081679
18    2010-01-01         Harris TX       NaN
19    2011-01-01         Harris TX -0.019901
20    2012-01-01         Harris TX -0.032121
21    2013-01-01         Harris TX  0.070297
22    2014-01-01         Harris TX  0.126779
23    2015-01-01         Harris TX  0.188205
24    2016-01-01         Harris TX  0.091277
25    2017-01-01         Harris TX -0.004711
26    2018-01-01         Harris TX  0.047325
27    2010-01-01       Maricopa AZ       NaN
28    2011-01-01       Maricopa AZ       NaN
29    2012-01-01       Maricopa AZ       NaN
...          ...               ...       ...
17961 2016-01-01      Cabo Rojo PR -0.076569
17962 2017-01-01      Cabo Rojo PR -0.031273
17963 2018-01-01      Cabo Rojo PR -0.030526
17964 2010-01-01   Saint Thomas VI       NaN
17965 2011-01-01   Saint Thomas VI       NaN
17966 2012-01-01   Saint Thomas VI       NaN
17967 2013-01-01   Saint Thomas VI       NaN
17968 2014-01-01   Saint Thomas VI       NaN
17969 2015-01-01   Saint Thomas VI  0.158508
17970 2016-01-01   Saint Thomas VI  0.031599
17971 2017-01-01   Saint Thomas VI  0.108883
17972 2018-01-01   Saint Thomas VI  0.000107
17973 2010-01-01  Trujillo Alto PR       NaN
17974 2011-01-01  Trujillo Alto PR       NaN
17975 2012-01-01  Trujillo Alto PR       NaN
17976 2013-01-01  Trujillo Alto PR       NaN
17977 2014-01-01  Trujillo Alto PR       NaN
17978 2015-01-01  Trujillo Alto PR       NaN
17979 2016-01-01  Trujillo Alto PR -0.020392
17980 2017-01-01  Trujillo Alto PR -0.091399
17981 2018-01-01  Trujillo Alto PR  0.028249
17982 2010-01-01             month       NaN
17983 2011-01-01             month  0.000000
17984 2012-01-01             month  0.000000
17985 2013-01-01             month  0.000000
17986 2014-01-01             month  0.000000
17987 2015-01-01             month  0.000000
17988 2016-01-01             month  0.000000
17989 2017-01-01             month  0.000000
17990 2018-01-01             month  0.000000

[17991 rows x 3 columns]