In [4]:
import pandas as pd

In [17]:

Zip_Zhvi_AllHomes = pd.read_csv('http://files.zillowstatic.com/research/public/Zip/Zip_Zhvi_AllHomes.csv')
#Zip_Zhvi_AllHomes.iloc[1,:]

RegionID        84654
RegionName      60657
City          Chicago
State              IL
Metro         Chicago
CountyName       Cook
SizeRank            2
1996-04        146700
1996-05        146500
1996-06        146300
1996-07        146300
1996-08        146800
1996-09        147100
1996-10        147300
1996-11        147800
1996-12        148600
1997-01        149100
1997-02        149600
1997-03        151100
1997-04        153200
1997-05        155100
1997-06        157200
1997-07        159100
1997-08        160000
1997-09        160800
1997-10        162200
1997-11        163200
1997-12        164100
1998-01        165600
1998-02        167400
               ...
2015-08        308300
2015-09        308500
2015-10        310100
2015-11        311100
2015-12        310500
2016-01        310900
2016-02        312200
2016-03        314000
2016-04        316100
2016-05        316700
2016-06        316600
2016-07        316500
2016-08        316800
2016-09        316400
2016-10        316300
2016-11        316800
2016-12        318300
2017-01        319000
2017-02        319900
2017-03        321200
2017-04        323000
2017-05        324600
2017-06        325200
2017-07        324300
2017-08        324000
2017-09        324500
2017-10        324200
2017-11        322500
2017-12        320400
2018-01        319700
Name: 1, Length: 269, dtype: object

In [68]:
Zip_Zhvi_AllHomesT= Zip_Zhvi_AllHomes.transpose()
 #.iloc[0,:]
#df.drop()
Zip_Zhvi_AllHomesT.drop(Zip_Zhvi_AllHomesT.index[2:7], inplace= True)
Zip_Zhvi_AllHomesT.drop(Zip_Zhvi_AllHomesT.index[0], inplace= True)
Zip_Zhvi_AllHomesT.columns = Zip_Zhvi_AllHomesT.iloc[0]
Zip_Zhvi_AllHomesT.drop(Zip_Zhvi_AllHomesT.index[0], inplace= True)
Zip_Zhvi_AllHomesT = Zip_Zhvi_AllHomesT.pct_change()

Zip_Zhvi_AllHomesT = Zip_Zhvi_AllHomesT.reset_index()

#>>> pd.melt(df, id_vars=['A'], value_vars=['B', 'C'])
Zip_Zhvi_AllHomesT

RegionName,index,10025,60657,60614,79936,60640,10467,77084,94109,75070,...,12429,54844,97028,12720,1338,97102,36564,3293,21405,85220
0,1996-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1996-05,NaN,-0.001363,-0.012626,0.002825,-0.009775,NaN,-0.002646,-0.008384,NaN,...,0.001326,-0.000498,NaN,-0.007299,-0.008089,NaN,NaN,0.013228,0.001972,NaN
2,1996-06,NaN,-0.001365,-0.006650,0.000000,-0.005923,NaN,-0.003979,0.002367,NaN,...,0.003974,0.000498,NaN,0.026471,-0.003058,NaN,NaN,0.031332,0.005118,NaN
3,1996-07,NaN,0.000000,-0.002060,0.005634,-0.000993,NaN,0.000000,0.007085,NaN,...,0.006596,0.000000,NaN,0.008596,-0.002045,NaN,NaN,0.000000,0.011359,NaN
4,1996-08,NaN,0.003418,0.000516,-0.002801,0.000994,NaN,-0.002663,0.001005,NaN,...,0.011796,-0.000498,NaN,-0.048295,-0.007172,NaN,NaN,-0.043038,0.010844,NaN
5,1996-09,NaN,0.002044,0.003094,0.005618,0.005958,NaN,-0.002670,0.000335,NaN,...,0.003886,0.000000,NaN,-0.073134,-0.005160,NaN,NaN,-0.037037,0.009195,NaN
6,1996-10,NaN,0.001360,0.007198,0.013966,0.009872,NaN,-0.001339,-0.000669,NaN,...,-0.001290,0.000000,NaN,-0.032206,-0.004149,NaN,NaN,-0.021978,0.013667,NaN
7,1996-11,NaN,0.003394,0.010209,0.006887,0.008798,NaN,0.005362,-0.005022,NaN,...,-0.005168,0.000498,NaN,-0.011647,0.001042,NaN,NaN,-0.018258,0.029213,NaN
8,1996-12,NaN,0.005413,0.011117,-0.004104,0.011628,NaN,0.006667,0.002019,NaN,...,0.000000,0.000000,NaN,0.000000,0.005203,NaN,NaN,-0.001431,0.027293,NaN
9,1997-01,NaN,0.003365,-0.001999,0.000000,0.007663,NaN,0.006623,0.017126,NaN,...,0.007792,0.000000,NaN,0.006734,0.004141,NaN,NaN,0.005731,0.012044,NaN
10,1997-02,NaN,0.003353,-0.010015,0.001374,0.003802,NaN,0.003947,0.024100,0.011303,...,0.009021,0.000000,NaN,0.015050,-0.002062,NaN,NaN,-0.009972,-0.000350,NaN
11,1997-03,NaN,0.010027,-0.000506,0.002743,0.007576,NaN,0.005242,0.015152,0.000657,...,0.003831,0.000000,NaN,0.014827,0.001033,NaN,NaN,-0.010072,0.000350,NaN
12,1997-04,NaN,0.013898,0.010628,0.000000,0.003759,NaN,0.006519,0.011115,0.000657,...,-0.008906,0.000000,NaN,0.011364,0.003096,NaN,NaN,0.001453,-0.000350,NaN
13,1997-05,NaN,0.012402,0.004006,0.002736,-0.001873,NaN,0.007772,0.013191,0.000657,...,-0.010270,-0.000498,NaN,0.006421,0.006173,NaN,NaN,0.000000,0.005602,NaN
14,1997-06,NaN,0.013540,0.002494,0.002729,0.002814,NaN,0.006427,0.013019,0.000000,...,-0.001297,0.000498,NaN,0.009569,-0.002045,NaN,NaN,-0.008708,0.005919,NaN
15,1997-07,NaN,0.012087,0.005473,0.005442,0.009355,NaN,0.007663,0.014382,0.001312,...,0.001299,0.000000,NaN,0.022117,-0.003074,NaN,NaN,-0.002928,0.003461,NaN
16,1997-08,NaN,0.005657,0.002969,0.008119,0.011121,NaN,0.007605,0.018401,0.002621,...,-0.009079,-0.000498,NaN,0.034003,-0.002055,NaN,NaN,0.007342,0.001035,NaN
17,1997-09,NaN,0.005000,-0.001973,0.005369,0.004583,NaN,0.006289,0.006517,0.007843,...,-0.003927,0.000000,NaN,0.020927,0.003090,NaN,NaN,0.020408,0.006892,NaN
18,1997-10,NaN,0.008706,0.000989,0.004005,-0.005474,NaN,0.002500,0.000883,0.005837,...,0.000000,0.000000,NaN,0.008785,0.009240,NaN,NaN,0.021429,0.001027,NaN
19,1997-11,NaN,0.006165,0.002469,0.002660,-0.007339,NaN,0.002494,0.017054,0.003224,...,-0.002628,0.000000,NaN,-0.002903,0.009156,NaN,NaN,0.005594,-0.002051,NaN
20,1997-12,NaN,0.005515,0.000985,0.005305,-0.002773,NaN,0.001244,0.023706,0.004499,...,-0.001318,0.000498,NaN,-0.010189,0.005040,NaN,NaN,-0.002782,0.008222,NaN
21,1998-01,NaN,0.009141,0.002953,0.005277,0.000000,NaN,0.001242,0.012991,0.008957,...,0.005277,0.000000,NaN,-0.013235,0.006018,NaN,NaN,0.008368,0.025144,NaN
22,1998-02,NaN,0.010870,0.006869,0.003937,0.000927,NaN,0.001241,0.014497,0.007609,...,0.006562,0.000000,NaN,-0.004471,0.008973,NaN,NaN,0.001383,0.013921,NaN
23,1998-03,NaN,0.003584,0.008285,0.002614,0.008333,NaN,0.002478,0.022534,0.004405,...,0.014342,0.000000,NaN,0.005988,0.003953,NaN,NaN,-0.016575,0.003269,0.003645
24,1998-04,NaN,0.000595,0.010633,-0.002608,0.018365,NaN,0.003708,0.020156,-0.001253,...,0.016710,0.000000,NaN,0.007440,0.002953,NaN,NaN,-0.025281,0.011730,-0.001211
25,1998-05,NaN,0.002380,0.008608,-0.001307,0.017133,NaN,0.004926,0.016860,-0.003764,...,0.018963,0.000000,NaN,-0.004431,0.007851,NaN,NaN,-0.010086,0.021578,-0.001212
26,1998-06,NaN,0.002374,0.013276,0.001309,0.011525,NaN,0.004902,0.016580,-0.006297,...,0.009926,0.000000,NaN,-0.026706,0.014606,NaN,NaN,-0.002911,0.013556,0.000000
27,1998-07,NaN,0.001184,0.017314,-0.002614,0.011394,NaN,0.007317,0.019113,-0.007605,...,-0.004914,0.000000,NaN,-0.021341,0.011516,NaN,NaN,0.018978,0.000311,0.004854
28,1998-08,NaN,0.006505,0.014719,-0.002621,0.008666,NaN,0.006053,0.017754,-0.003193,...,-0.011111,-0.000498,NaN,-0.001558,0.009488,NaN,NaN,0.031519,-0.001244,-0.002415
29,1998-09,NaN,0.011163,0.007253,-0.002628,0.005155,NaN,0.004813,0.013514,0.001922,...,-0.001248,0.000000,NaN,0.020281,0.006579,NaN,NaN,0.030556,0.001868,-0.007264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,2015-08,0.018515,-0.001619,0.007283,0.000000,-0.006234,-0.006873,0.006338,0.011413,0.007105,...,-0.014277,0.010160,-0.003093,0.010142,0.004771,0.011022,0.010469,0.000000,-0.001362,0.008855
233,2015-09,0.021567,0.000649,0.018632,0.000000,0.004182,0.002517,0.009097,0.002799,0.008169,...,-0.011335,-0.004310,-0.007757,0.019076,0.000475,0.008792,0.004583,-0.002435,-0.003844,0.015214
234,2015-10,0.006635,0.005186,0.030576,0.000895,0.009891,0.002510,0.009709,0.002071,0.006630,...,-0.007643,-0.013709,-0.006567,0.018719,-0.004746,-0.000697,0.001785,-0.007322,-0.005975,0.017291
235,2015-11,0.001997,0.003225,0.020927,-0.001789,0.004639,0.001252,0.008242,0.005301,0.006220,...,0.002567,0.018288,-0.001574,0.013540,-0.006199,0.004710,0.013265,-0.010449,-0.001377,0.009632
236,2015-12,0.010864,-0.001929,0.009860,-0.002688,0.000513,0.005314,0.006812,0.009115,0.008000,...,0.010243,0.028017,0.002207,0.015267,0.000000,0.018750,0.019539,0.003727,0.002633,0.006173
237,2016-01,0.013410,0.001288,0.008222,-0.000898,0.001538,0.009639,0.006766,0.011778,0.010823,...,0.010139,0.007687,-0.003146,0.015038,0.003359,0.019257,0.006324,0.011139,-0.002001,0.002231
238,2016-02,0.019167,0.004181,0.009684,0.000000,0.000512,0.010779,0.010081,0.005864,0.011420,...,0.010665,0.007628,-0.001262,0.008333,0.000478,0.028256,-0.002285,0.007956,-0.007018,-0.006678
239,2016-03,0.018902,0.005766,0.007824,0.000000,-0.001535,0.010664,0.005988,-0.004003,0.008821,...,0.008690,0.014453,0.005055,0.001837,-0.005258,0.027967,-0.003818,0.003036,-0.007067,-0.011204
240,2016-04,0.003467,0.006688,0.008515,0.002698,0.002050,0.006934,0.006614,-0.011532,0.005946,...,0.008615,0.006784,0.010688,0.004583,-0.008650,0.011547,-0.003066,0.009080,-0.002034,-0.006799
241,2016-05,-0.004015,0.001898,-0.000993,0.004484,0.000000,0.006287,0.008541,-0.015556,0.006954,...,0.001830,-0.002695,0.005599,0.003650,-0.004847,-0.006880,-0.007111,0.009598,0.003821,-0.005134
242,2016-06,0.007687,-0.000316,-0.005966,0.004464,0.008696,0.004165,0.020195,-0.013647,0.010704,...,0.001218,-0.002027,-0.003712,-0.003636,-0.000487,-0.017163,-0.010453,0.008318,-0.001142,-0.000573
243,2016-07,0.015071,-0.000316,-0.004501,0.006222,0.008114,0.011852,0.021711,-0.003550,0.010591,...,0.006083,-0.001354,-0.006209,-0.010036,0.000000,-0.022269,-0.011541,0.002357,-0.000889,0.004016
244,2016-08,0.015672,0.000948,0.000000,0.004417,-0.001006,0.021962,0.007500,0.003654,0.006761,...,0.009069,0.000000,-0.004374,-0.010138,0.005361,-0.008029,-0.013259,-0.000588,0.002670,0.003429
245,2016-09,0.004151,-0.001263,0.003266,0.000000,-0.005539,0.019198,-0.004963,0.003914,0.003694,...,0.003595,0.003390,-0.003765,-0.009311,0.011634,0.006442,-0.012635,0.004118,0.001268,0.003417
246,2016-10,-0.000180,-0.000316,0.011017,0.000880,0.002532,0.007591,-0.001247,0.004080,0.005688,...,0.001791,0.004054,-0.004724,-0.007519,0.008625,0.018054,-0.006500,0.010545,-0.003039,0.006810
247,2016-11,0.015729,0.001581,0.021050,0.003515,0.004040,0.001395,0.000000,0.008307,0.007319,...,0.004172,-0.001346,0.000000,-0.009470,0.002850,0.019507,-0.005111,0.012754,-0.005843,0.009019
248,2016-12,0.007875,0.004735,0.008732,0.003503,0.006539,-0.003065,-0.007491,0.007970,0.004954,...,0.002374,-0.003369,-0.004747,-0.007648,0.006158,0.015655,0.009864,0.003434,-0.001150,0.007263
249,2017-01,-0.009658,0.002199,-0.000962,0.003490,0.008496,-0.002795,-0.013208,0.003287,0.003615,...,0.000000,-0.006085,-0.015580,-0.002890,0.007062,0.013234,0.020350,-0.005134,-0.002174,0.008319
250,2017-02,-0.007270,0.002821,0.000963,0.000000,0.009911,0.005325,-0.014022,0.002125,0.006221,...,0.003552,-0.006122,-0.014858,0.000966,0.006078,-0.003995,0.025728,-0.009174,-0.012819,0.008251
251,2017-03,0.002679,0.004064,-0.012503,-0.001739,0.006869,0.010315,-0.007757,0.004506,0.008135,...,0.010029,-0.004107,-0.003607,0.008687,0.006506,-0.024529,0.021194,-0.013310,-0.012206,0.005456
252,2017-04,0.017367,0.005604,-0.026297,-0.000871,-0.001462,0.008278,0.005212,0.008181,0.007747,...,0.007009,-0.011684,0.001645,0.017225,0.008310,-0.020244,0.017708,-0.014076,0.002761,0.000543
253,2017-05,0.041058,0.004954,0.004251,0.000872,-0.002928,0.003558,0.016850,0.006369,0.007367,...,0.006961,-0.015994,0.011827,0.014111,0.005495,-0.016142,0.005613,0.001190,0.011930,0.002711
254,2017-06,0.051379,0.001848,0.021912,-0.002613,0.000979,0.002454,0.010198,0.003641,0.003180,...,0.005760,-0.002827,0.020455,0.003711,0.002732,-0.015751,0.004837,0.011884,0.009328,0.008112
255,2017-07,0.035671,-0.002768,0.001462,-0.002620,0.008313,0.002448,0.005678,-0.001987,-0.000317,...,0.000573,0.012757,0.020999,0.000924,-0.000454,0.003834,0.003518,0.007046,0.002824,0.012339
256,2017-08,0.008109,-0.000925,-0.006326,0.000876,0.012124,0.007870,0.010038,-0.002077,0.002536,...,-0.001717,0.015395,0.014646,0.003693,0.000454,0.022252,-0.008487,0.000000,-0.004992,0.011129
257,2017-09,-0.006588,0.001543,-0.004163,0.004374,0.006229,0.014540,0.009317,0.005031,0.008855,...,0.009174,0.012405,0.005835,0.004600,0.003179,0.013320,-0.021585,-0.003499,-0.005403,0.004193
258,2017-10,-0.005167,-0.000924,-0.010327,0.000871,-0.002857,0.011146,0.002462,0.011737,0.007210,...,0.016477,0.002042,-0.000916,0.008242,0.003622,0.006092,-0.024344,-0.007022,0.000129,-0.001044
259,2017-11,-0.015038,-0.005244,-0.016646,-0.002611,-0.001910,0.007612,-0.001842,0.011089,0.001556,...,0.007267,-0.008832,0.001222,0.019982,0.010374,0.008126,-0.001949,-0.001768,0.000905,-0.005225
260,2017-12,-0.026363,-0.006512,-0.006316,-0.000873,0.000957,0.004168,-0.001845,0.001350,-0.000622,...,-0.002775,-0.003427,0.003053,0.020481,-0.010714,0.004742,0.003125,0.005313,-0.009302,-0.003676
261,2018-01,-0.019964,-0.002185,0.003814,0.002620,0.003824,-0.001816,0.000616,-0.005645,0.000311,...,-0.002226,0.002063,-0.000304,0.007853,-0.028430,0.001416,-0.004868,0.002936,-0.006781,0.002636

In [69]:
#Zip_Zhvi_AllHomes.count()

In [70]:
Zip_Zhvi_AllHomesT = pd.melt(Zip_Zhvi_AllHomesT,  id_vars='index', var_name='zip', value_name='price')
Zip_Zhvi_AllHomesT

           index    zip     price
0        1996-04  10025       NaN
1        1996-05  10025       NaN
2        1996-06  10025       NaN
3        1996-07  10025       NaN
4        1996-08  10025       NaN
5        1996-09  10025       NaN
6        1996-10  10025       NaN
7        1996-11  10025       NaN
8        1996-12  10025       NaN
9        1997-01  10025       NaN
10       1997-02  10025       NaN
11       1997-03  10025       NaN
12       1997-04  10025       NaN
13       1997-05  10025       NaN
14       1997-06  10025       NaN
15       1997-07  10025       NaN
16       1997-08  10025       NaN
17       1997-09  10025       NaN
18       1997-10  10025       NaN
19       1997-11  10025       NaN
20       1997-12  10025       NaN
21       1998-01  10025       NaN
22       1998-02  10025       NaN
23       1998-03  10025       NaN
24       1998-04  10025       NaN
25       1998-05  10025       NaN
26       1998-06  10025       NaN
27       1998-07  10025       NaN
28       1998-08  10025       NaN
29       1998-09  10025       NaN
...          ...    ...       ...
4015644  2015-08  85220  0.008855
4015645  2015-09  85220  0.015214
4015646  2015-10  85220  0.017291
4015647  2015-11  85220  0.009632
4015648  2015-12  85220  0.006173
4015649  2016-01  85220  0.002231
4015650  2016-02  85220 -0.006678
4015651  2016-03  85220 -0.011204
4015652  2016-04  85220 -0.006799
4015653  2016-05  85220 -0.005134
4015654  2016-06  85220 -0.000573
4015655  2016-07  85220  0.004016
4015656  2016-08  85220  0.003429
4015657  2016-09  85220  0.003417
4015658  2016-10  85220  0.006810
4015659  2016-11  85220  0.009019
4015660  2016-12  85220  0.007263
4015661  2017-01  85220  0.008319
4015662  2017-02  85220  0.008251
4015663  2017-03  85220  0.005456
4015664  2017-04  85220  0.000543
4015665  2017-05  85220  0.002711
4015666  2017-06  85220  0.008112
4015667  2017-07  85220  0.012339
4015668  2017-08  85220  0.011129
4015669  2017-09  85220  0.004193
4015670  2017-10  85220 -0.001044
4015671  2017-11  85220 -0.005225
4015672  2017-12  85220 -0.003676
4015673  2018-01  85220  0.002636

[4015674 rows x 3 columns]

In [71]:
from datetime import datetime
datestring = "2008-12"
dt = datetime.strptime(datestring, '%Y-%m')
print (dt.year, dt.month, dt.day)

2008 12 1

In [72]:
Zip_Zhvi_AllHomesT['index'] =  pd.to_datetime(Zip_Zhvi_AllHomesT['index'], format='%Y-%m')
Zip_Zhvi_AllHomesT

             index    zip     price
0       1996-04-01  10025       NaN
1       1996-05-01  10025       NaN
2       1996-06-01  10025       NaN
3       1996-07-01  10025       NaN
4       1996-08-01  10025       NaN
5       1996-09-01  10025       NaN
6       1996-10-01  10025       NaN
7       1996-11-01  10025       NaN
8       1996-12-01  10025       NaN
9       1997-01-01  10025       NaN
10      1997-02-01  10025       NaN
11      1997-03-01  10025       NaN
12      1997-04-01  10025       NaN
13      1997-05-01  10025       NaN
14      1997-06-01  10025       NaN
15      1997-07-01  10025       NaN
16      1997-08-01  10025       NaN
17      1997-09-01  10025       NaN
18      1997-10-01  10025       NaN
19      1997-11-01  10025       NaN
20      1997-12-01  10025       NaN
21      1998-01-01  10025       NaN
22      1998-02-01  10025       NaN
23      1998-03-01  10025       NaN
24      1998-04-01  10025       NaN
25      1998-05-01  10025       NaN
26      1998-06-01  10025       NaN
27      1998-07-01  10025       NaN
28      1998-08-01  10025       NaN
29      1998-09-01  10025       NaN
...            ...    ...       ...
4015644 2015-08-01  85220  0.008855
4015645 2015-09-01  85220  0.015214
4015646 2015-10-01  85220  0.017291
4015647 2015-11-01  85220  0.009632
4015648 2015-12-01  85220  0.006173
4015649 2016-01-01  85220  0.002231
4015650 2016-02-01  85220 -0.006678
4015651 2016-03-01  85220 -0.011204
4015652 2016-04-01  85220 -0.006799
4015653 2016-05-01  85220 -0.005134
4015654 2016-06-01  85220 -0.000573
4015655 2016-07-01  85220  0.004016
4015656 2016-08-01  85220  0.003429
4015657 2016-09-01  85220  0.003417
4015658 2016-10-01  85220  0.006810
4015659 2016-11-01  85220  0.009019
4015660 2016-12-01  85220  0.007263
4015661 2017-01-01  85220  0.008319
4015662 2017-02-01  85220  0.008251
4015663 2017-03-01  85220  0.005456
4015664 2017-04-01  85220  0.000543
4015665 2017-05-01  85220  0.002711
4015666 2017-06-01  85220  0.008112
4015667 2017-07-01  85220  0.012339
4015668 2017-08-01  85220  0.011129
4015669 2017-09-01  85220  0.004193
4015670 2017-10-01  85220 -0.001044
4015671 2017-11-01  85220 -0.005225
4015672 2017-12-01  85220 -0.003676
4015673 2018-01-01  85220  0.002636

[4015674 rows x 3 columns]

In [73]:
Zip_Zhvi_AllHomesT

             index    zip     price
0       1996-04-01  10025       NaN
1       1996-05-01  10025       NaN
2       1996-06-01  10025       NaN
3       1996-07-01  10025       NaN
4       1996-08-01  10025       NaN
5       1996-09-01  10025       NaN
6       1996-10-01  10025       NaN
7       1996-11-01  10025       NaN
8       1996-12-01  10025       NaN
9       1997-01-01  10025       NaN
10      1997-02-01  10025       NaN
11      1997-03-01  10025       NaN
12      1997-04-01  10025       NaN
13      1997-05-01  10025       NaN
14      1997-06-01  10025       NaN
15      1997-07-01  10025       NaN
16      1997-08-01  10025       NaN
17      1997-09-01  10025       NaN
18      1997-10-01  10025       NaN
19      1997-11-01  10025       NaN
20      1997-12-01  10025       NaN
21      1998-01-01  10025       NaN
22      1998-02-01  10025       NaN
23      1998-03-01  10025       NaN
24      1998-04-01  10025       NaN
25      1998-05-01  10025       NaN
26      1998-06-01  10025       NaN
27      1998-07-01  10025       NaN
28      1998-08-01  10025       NaN
29      1998-09-01  10025       NaN
...            ...    ...       ...
4015644 2015-08-01  85220  0.008855
4015645 2015-09-01  85220  0.015214
4015646 2015-10-01  85220  0.017291
4015647 2015-11-01  85220  0.009632
4015648 2015-12-01  85220  0.006173
4015649 2016-01-01  85220  0.002231
4015650 2016-02-01  85220 -0.006678
4015651 2016-03-01  85220 -0.011204
4015652 2016-04-01  85220 -0.006799
4015653 2016-05-01  85220 -0.005134
4015654 2016-06-01  85220 -0.000573
4015655 2016-07-01  85220  0.004016
4015656 2016-08-01  85220  0.003429
4015657 2016-09-01  85220  0.003417
4015658 2016-10-01  85220  0.006810
4015659 2016-11-01  85220  0.009019
4015660 2016-12-01  85220  0.007263
4015661 2017-01-01  85220  0.008319
4015662 2017-02-01  85220  0.008251
4015663 2017-03-01  85220  0.005456
4015664 2017-04-01  85220  0.000543
4015665 2017-05-01  85220  0.002711
4015666 2017-06-01  85220  0.008112
4015667 2017-07-01  85220  0.012339
4015668 2017-08-01  85220  0.011129
4015669 2017-09-01  85220  0.004193
4015670 2017-10-01  85220 -0.001044
4015671 2017-11-01  85220 -0.005225
4015672 2017-12-01  85220 -0.003676
4015673 2018-01-01  85220  0.002636

[4015674 rows x 3 columns]

In [59]:
AllRegionsForePublic = pd.read_csv('http://files.zillowstatic.com/research/public/AllRegionsForePublic.csv')

,Region,RegionName,State,ForecastYoYPctChange,MSAName,CountyName,CityName
0,National,United States,US,3.078073,NaN,NaN,NaN
1,MSA,"Akron, OH",OH,2.515573,"Akron, OH",NaN,NaN
2,MSA,"Albany, GA",GA,3.579034,"Albany, GA",NaN,NaN
3,MSA,"Albany, NY",NY,3.086973,"Albany, NY",NaN,NaN
4,MSA,"Albuquerque, NM",NM,2.859574,"Albuquerque, NM",NaN,NaN
5,MSA,"Alexandria, LA",LA,2.003955,"Alexandria, LA",NaN,NaN
6,MSA,"Allentown, PA",PA,1.976884,"Allentown, PA",NaN,NaN
7,MSA,"Altoona, PA",PA,1.364871,"Altoona, PA",NaN,NaN
8,MSA,"Amarillo, TX",TX,2.140482,"Amarillo, TX",NaN,NaN
9,MSA,"Ames, IA",IA,3.987445,"Ames, IA",NaN,NaN
10,MSA,"Anchorage, AK",AK,5.412158,"Anchorage, AK",NaN,NaN
11,MSA,"Ann Arbor, MI",MI,4.785821,"Ann Arbor, MI",NaN,NaN
12,MSA,"Appleton, WI",WI,3.520030,"Appleton, WI",NaN,NaN
13,MSA,"Asheville, NC",NC,2.270682,"Asheville, NC",NaN,NaN
14,MSA,"Athens, GA",GA,3.765132,"Athens, GA",NaN,NaN
15,MSA,"Atlanta, GA",GA,3.645099,"Atlanta, GA",NaN,NaN
16,MSA,"Atlantic City, NJ",NJ,3.167554,"Atlantic City, NJ",NaN,NaN
17,MSA,"Auburn, AL",AL,2.892657,"Auburn, AL",NaN,NaN
18,MSA,"Augusta, GA",GA,3.121328,"Augusta, GA",NaN,NaN
19,MSA,"Austin, TX",TX,1.914706,"Austin, TX",NaN,NaN
20,MSA,"Bakersfield, CA",CA,4.011702,"Bakersfield, CA",NaN,NaN
21,MSA,"Baltimore, MD",MD,1.623232,"Baltimore, MD",NaN,NaN
22,MSA,"Bangor, ME",ME,4.751449,"Bangor, ME",NaN,NaN
23,MSA,"Cape Cod, MA",MA,3.112330,"Cape Cod, MA",NaN,NaN
24,MSA,"Baton Rouge, LA",LA,2.990687,"Baton Rouge, LA",NaN,NaN
25,MSA,"Battle Creek, MI",MI,3.177922,"Battle Creek, MI",NaN,NaN
26,MSA,"Bay City, MI",MI,3.344374,"Bay City, MI",NaN,NaN
27,MSA,"Bellingham, WA",WA,2.997830,"Bellingham, WA",NaN,NaN
28,MSA,"Bend, OR",OR,1.088562,"Bend, OR",NaN,NaN
29,MSA,"Billings, MT",MT,3.832449,"Billings, MT",NaN,NaN
...,...,...,...,...,...,...,...
22368,ZipCode,97317,OR,6.251949,"Salem, OR",Marion,Four Corners
22369,ZipCode,60642,IL,1.623506,"Chicago, IL",Cook,Chicago
22370,ZipCode,61705,IL,3.067968,"Bloomington, IL",McLean,Bloomington
22371,ZipCode,81507,CO,0.644957,"Grand Junction, CO",Mesa,Grand Junction
22372,ZipCode,84081,UT,2.661701,"Salt Lake City, UT",Salt Lake,West Jordan
22373,ZipCode,85756,AZ,4.411510,"Tucson, AZ",Pima,Tucson
22374,ZipCode,86315,AZ,2.178622,"Prescott, AZ",Yavapai,Prescott Valley
22375,ZipCode,85118,AZ,1.153896,"Phoenix, AZ",Pinal,Gold Canyon
22376,ZipCode,85119,AZ,2.201336,"Phoenix, AZ",Pinal,Apache Junction
22377,ZipCode,85122,AZ,2.265596,"Phoenix, AZ",Pinal,Casa Grande
22378,ZipCode,85128,AZ,2.934060,"Phoenix, AZ",Pinal,Coolidge
22379,ZipCode,85131,AZ,5.141441,"Phoenix, AZ",Pinal,Eloy
22380,ZipCode,85132,AZ,2.250587,"Phoenix, AZ",Pinal,Florence
22381,ZipCode,85137,AZ,3.754152,"Phoenix, AZ",Pinal,Kearny
22382,ZipCode,85138,AZ,2.055506,"Phoenix, AZ",Pinal,Maricopa
22383,ZipCode,85139,AZ,2.090948,"Phoenix, AZ",Pinal,Maricopa
22384,ZipCode,85142,AZ,2.170574,"Phoenix, AZ",Maricopa,Queen Creek
22385,ZipCode,85145,AZ,4.031478,"Tucson, AZ",Pima,Marana
22386,ZipCode,85194,AZ,1.528291,"Phoenix, AZ",Pinal,Casa Grande
22387,ZipCode,50324,IA,3.915121,"Des Moines, IA",Polk,Windsor Heights
22388,ZipCode,60484,IL,2.701492,"Chicago, IL",Will,University Park
22389,ZipCode,19060,PA,1.452568,"Philadelphia, PA",Delaware,Garnet Valley
22390,ZipCode,85123,AZ,2.764789,"Phoenix, AZ",Pinal,Casa Grande
22391,ZipCode,60958,IL,3.020574,"Kankakee, IL",Kankakee,Hopkins Park
22392,ZipCode,93737,CA,5.642485,"Fresno, CA",Fresno,Fresno
22393,ZipCode,84129,UT,3.675739,"Salt Lake City, UT",Salt Lake,Taylorsville
22394,ZipCode,75033,TX,1.487044,"Dallas-Fort Worth, TX",Collin,Frisco
22395,ZipCode,84009,UT,3.921859,"Salt Lake City, UT",Salt Lake,South Jordan
22396,ZipCode,86005,AZ,0.806701,"Flagstaff, AZ",Coconino,Flagstaff
22397,ZipCode,97003,OR,4.681196,"Portland, OR",Washington,Beaverton

In [60]:
AllRegionsForePublic.head()

,Region,RegionName,State,ForecastYoYPctChange,MSAName,CountyName,CityName
0,National,United States,US,3.078073,NaN,NaN,NaN
1,MSA,"Akron, OH",OH,2.515573,"Akron, OH",NaN,NaN
2,MSA,"Albany, GA",GA,3.579034,"Albany, GA",NaN,NaN
3,MSA,"Albany, NY",NY,3.086973,"Albany, NY",NaN,NaN
4,MSA,"Albuquerque, NM",NM,2.859574,"Albuquerque, NM",NaN,NaN

In [5]:
coest2016alldata = pd.read_csv('https://www2.census.gov/programs-surveys/popest/datasets/2010-2016/counties/totals/co-est2016-alldata.csv',encoding = "ISO-8859-1")

In [6]:

coest2016alldata.shape

(3193, 116)

In [14]:
coest2016alldata.columns[67:77]

Index(['RESIDUAL2012', 'RESIDUAL2013', 'RESIDUAL2014', 'RESIDUAL2015',
       'RESIDUAL2016', 'GQESTIMATESBASE2010', 'GQESTIMATES2010',
       'GQESTIMATES2011', 'GQESTIMATES2012', 'GQESTIMATES2013'],
      dtype='object')

In [17]:
listofcols = coest2016alldata.columns #[67:77]
listofcols[77:87]

Index(['GQESTIMATES2014', 'GQESTIMATES2015', 'GQESTIMATES2016', 'RBIRTH2011',
       'RBIRTH2012', 'RBIRTH2013', 'RBIRTH2014', 'RBIRTH2015', 'RBIRTH2016',
       'RDEATH2011'],
      dtype='object')

In [24]:
lofc = []
for colname in listofcols:
    lofc.append( colname[:-4])
    #print(colname)

lofc = list(set(lofc))
lofc

['NATURALINC',
 'ST',
 'DEATHS',
 'CENSUS201',
 'RINTERNATIONALMIG',
 'RDEATH',
 'BIRTHS',
 'SU',
 'RNATURALINC',
 'RDOMESTICMIG',
 'RESIDUAL',
 'INTERNATIONALMIG',
 'CO',
 'POPESTIMATE',
 'GQESTIMATESBASE',
 'GQESTIMATES',
 'RE',
 'S',
 'DOMESTICMIG',
 'ESTIMATESBASE',
 'NETMIG',
 'CTY',
 'RNETMIG',
 'NPOPCHG_',
 'RBIRTH',
 'DIVI']

In [ ]:
coest2016alldata = pd.read_csv()