In [75]:
import quandl
import datetime as dt
import matplotlib.pyplot as plt

today=dt.date.today()
thirty_days=dt.timedelta(days=30)
thirty_days_ago=today-thirty_days
data = quandl.get("WIKI/AAPL", start_date=str(thirty_days_ago), end_date=str(today),column_index=4)
data.plot();
plt.show()
#data

In [8]:
#https://stackoverflow.com/questions/44088894/quandl-stock-api-historical-data

In [27]:
#WTI Data#
WTI_daily = quandl.get("WIKI/AAPL", collapse="daily",trim_start="1986-10-10", trim_end="1986-10-15")
#WTI_daily.columns = ['WTI']
WTI_daily

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
1986-10-10,32.88,33.38,32.38,33.25,261300.0,0.0,1.0,0.483429,0.490780,0.476077,0.488869,14632800.0
1986-10-13,33.13,34.63,33.00,34.63,445000.0,0.0,1.0,0.487104,0.509158,0.485193,0.509158,24920000.0
1986-10-14,34.63,35.25,33.75,34.00,889900.0,0.0,1.0,0.509158,0.518274,0.496220,0.499896,49834400.0
1986-10-15,33.50,33.50,32.75,33.38,917000.0,0.0,1.0,0.492544,0.492544,0.481517,0.490780,51352000.0

In [2]:
import pandas as pd
import os
import quandl
import time

auth_tok = "1LkmpypqJskJzKcpd2TV"

data = quandl.get("WIKI/KO", trim_start = "2000-12-12", trim_end = "2014-12-30", authtoken=auth_tok)

print(data)

             Open     High     Low  Close      Volume  Ex-Dividend  \
Date
2000-12-12  57.69  58.6900  57.630  58.00   4004100.0        0.000
2000-12-13  57.75  58.3100  57.250  57.81   3704900.0        0.000
2000-12-14  56.00  57.4400  55.750  57.00   5023800.0        0.000
2000-12-15  55.00  56.6900  53.500  53.50  13770200.0        0.000
2000-12-18  54.00  55.5600  53.630  54.88   5152300.0        0.000
2000-12-19  54.69  57.9400  54.690  56.75   5844100.0        0.000
2000-12-20  55.75  58.0000  55.560  56.25   6672100.0        0.000
2000-12-21  56.25  59.6300  56.130  59.38   5965400.0        0.000
2000-12-22  58.81  59.0000  57.500  58.88   3741800.0        0.000
2000-12-26  58.88  60.0000  58.620  60.00   2835000.0        0.000
2000-12-27  60.00  61.3800  60.000  60.56   3855500.0        0.000
2000-12-28  61.94  61.9400  60.560  61.06   2760400.0        0.000
2000-12-29  60.94  61.1300  60.190  60.94   2485200.0        0.000
2001-01-02  60.31  61.9400  60.250  60.81   5303000.0        0.000
2001-01-03  60.88  62.1900  59.060  59.25   6234800.0        0.000
2001-01-04  58.56  58.8800  56.750  57.56   7385300.0        0.000
2001-01-05  57.63  58.7500  57.500  57.69   3980100.0        0.000
2001-01-08  57.88  59.6900  57.810  58.63   4764600.0        0.000
2001-01-09  58.25  59.9400  57.630  59.38   4258100.0        0.000
2001-01-10  58.38  59.2500  57.880  59.13   3981600.0        0.000
2001-01-11  58.75  58.8800  57.130  57.38   3454500.0        0.000
2001-01-12  57.44  57.4400  56.250  56.63   3606000.0        0.000
2001-01-16  57.06  57.3100  56.190  57.00   3581800.0        0.000
2001-01-17  57.75  58.6900  57.060  57.94   3825900.0        0.000
2001-01-18  57.31  58.6900  56.940  57.13   3507200.0        0.000
2001-01-19  56.56  57.1300  55.310  55.81   4912100.0        0.000
2001-01-22  55.56  56.0600  55.190  55.69   3437300.0        0.000
2001-01-23  56.06  57.1900  55.440  56.88   3853900.0        0.000
2001-01-24  56.94  58.0600  56.130  58.06   4594700.0        0.000
2001-01-25  58.06  59.0000  57.810  58.63   3743400.0        0.000
...           ...      ...     ...    ...         ...          ...
2014-11-17  42.75  42.9900  42.730  42.92  10663996.0        0.000
2014-11-18  42.95  43.8600  42.750  43.53  26143194.0        0.000
2014-11-19  43.67  44.4297  43.560  44.22  25400726.0        0.000
2014-11-20  43.96  44.4200  43.850  44.25  13465246.0        0.000
2014-11-21  44.58  44.7400  44.280  44.50  14382572.0        0.000
2014-11-24  44.51  44.7800  44.200  44.27  12890423.0        0.000
2014-11-25  44.27  44.5900  44.120  44.43  10741655.0        0.000
2014-11-26  43.99  44.3650  43.970  44.29   9200463.0        0.305
2014-11-28  44.15  45.0000  44.150  44.83  10501972.0        0.000
2014-12-01  44.18  44.7650  44.130  44.55  10065657.0        0.000
2014-12-02  44.37  44.6700  44.230  44.54   9878097.0        0.000
2014-12-03  44.42  44.4400  43.760  43.80  15246481.0        0.000
2014-12-04  43.62  43.8400  43.370  43.50  13804776.0        0.000
2014-12-05  43.50  43.6100  43.200  43.53  12536928.0        0.000
2014-12-08  43.51  43.6300  43.090  43.14  12805439.0        0.000
2014-12-09  42.15  42.5310  41.670  42.04  25684146.0        0.000
2014-12-10  42.04  42.2400  41.560  41.60  18323855.0        0.000
2014-12-11  41.62  42.0100  41.500  41.53  16201423.0        0.000
2014-12-12  41.39  41.6100  40.870  40.91  18431431.0        0.000
2014-12-15  41.13  41.1800  40.560  40.57  23378508.0        0.000
2014-12-16  40.20  41.3100  39.800  40.39  23474819.0        0.000
2014-12-17  40.44  41.7600  40.380  41.55  20223938.0        0.000
2014-12-18  41.86  42.3900  41.750  42.39  18030396.0        0.000
2014-12-19  42.44  42.7900  41.890  41.95  24009502.0        0.000
2014-12-22  42.14  42.4400  42.090  42.35  11190862.0        0.000
2014-12-23  42.54  43.1400  42.470  42.97  13411064.0        0.000
2014-12-24  43.10  43.2300  42.920  42.94   6405910.0        0.000
2014-12-26  42.97  43.3000  42.930  42.96   6466883.0        0.000
2014-12-29  42.80  43.0600  42.490  42.86   8694509.0        0.000
2014-12-30  42.74  42.9900  42.651  42.76   9222049.0        0.000

            Split Ratio  Adj. Open  Adj. High   Adj. Low  Adj. Close  \
Date
2000-12-12          1.0  18.473945  18.794173  18.454732   18.573216
2000-12-13          1.0  18.493159  18.672487  18.333045   18.512373
2000-12-14          1.0  17.932760  18.393888  17.852703   18.252988
2000-12-15          1.0  17.612532  18.153717  17.132191   17.132191
2000-12-18          1.0  17.292305  17.791860  17.173820   17.574105
2000-12-19          1.0  17.513262  18.554002  17.513262   18.172931
2000-12-20          1.0  17.852703  18.573216  17.791860   18.012817
2000-12-21          1.0  18.012817  19.095187  17.974390   19.015130
2000-12-22          1.0  18.832601  18.893444  18.413102   18.855016
2000-12-26          1.0  18.855016  19.213672  18.771757   19.213672
2000-12-27          1.0  19.213672  19.655586  19.213672   19.392999
2000-12-28          1.0  19.834914  19.834914  19.392999   19.553113
2000-12-29          1.0  19.514686  19.575529  19.274515   19.514686
2001-01-02          1.0  19.312942  19.834914  19.293729   19.473056
2001-01-03          1.0  19.495472  19.914971  18.912657   18.973501
2001-01-04          1.0  18.752544  18.855016  18.172931   18.432316
2001-01-05          1.0  18.454732  18.813387  18.413102   18.473945
2001-01-08          1.0  18.534789  19.114401  18.512373   18.774960
2001-01-09          1.0  18.653273  19.194458  18.454732   19.015130
2001-01-10          1.0  18.694903  18.973501  18.534789   18.935073
2001-01-11          1.0  18.813387  18.855016  18.294618   18.374675
2001-01-12          1.0  18.393888  18.393888  18.012817   18.134504
2001-01-16          1.0  18.272202  18.352259  17.993604   18.252988
2001-01-17          1.0  18.493159  18.794173  18.272202   18.554002
2001-01-18          1.0  18.352259  18.794173  18.233774   18.294618
2001-01-19          1.0  18.112088  18.294618  17.711803   17.871917
2001-01-22          1.0  17.791860  17.951974  17.673376   17.833490
2001-01-23          1.0  17.951974  18.313831  17.753433   18.214561
2001-01-24          1.0  18.233774  18.592430  17.974390   18.592430
2001-01-25          1.0  18.592430  18.893444  18.512373   18.774960
...                 ...        ...        ...        ...         ...
2014-11-17          1.0  38.817804  39.035728  38.799644   38.972167
2014-11-18          1.0  38.999408  39.825705  38.817804   39.526059
2014-11-19          1.0  39.653181  40.343003  39.553299   40.152592
2014-11-20          1.0  39.916507  40.334195  39.816625   40.179832
2014-11-21          1.0  40.479478  40.624761  40.207073   40.406837
2014-11-24          1.0  40.415917  40.661082  40.134431   40.197992
2014-11-25          1.0  40.197992  40.488558  40.061790   40.343275
2014-11-26          1.0  40.218817  40.561669  40.200532   40.493099
2014-11-28          1.0  40.365101  41.142232  40.365101   40.986805
2014-12-01          1.0  40.392529  40.927378  40.346815   40.730809
2014-12-02          1.0  40.566240  40.840522  40.438242   40.721667
2014-12-03          1.0  40.611954  40.630239  40.008535   40.045105
2014-12-04          1.0  39.880536  40.081676  39.651969   39.770824
2014-12-05          1.0  39.770824  39.871394  39.496542   39.798252
2014-12-08          1.0  39.779967  39.889679  39.395972   39.441686
2014-12-09          1.0  38.536557  38.884894  38.097706   38.435987
2014-12-10          1.0  38.435987  38.618841  37.997137   38.033707
2014-12-11          1.0  38.051993  38.408559  37.942280   37.969708
2014-12-12          1.0  37.841710  38.042850  37.366289   37.402860
2014-12-15          1.0  37.604000  37.649713  37.082865   37.092007
2014-12-16          1.0  36.753727  37.768569  36.388018   36.927439
2014-12-17          1.0  36.973152  38.179991  36.918296   37.987994
2014-12-18          1.0  38.271418  38.755982  38.170848   38.755982
2014-12-19          1.0  38.801696  39.121691  38.298846   38.353703
2014-12-22          1.0  38.527414  38.801696  38.481701   38.719411
2014-12-23          1.0  38.893123  39.441686  38.829124   39.286260
2014-12-24          1.0  39.405115  39.523970  39.240546   39.258832
2014-12-26          1.0  39.286260  39.587969  39.249689   39.277117
2014-12-29          1.0  39.130834  39.368544  38.847409   39.185690
2014-12-30          1.0  39.075977  39.304545  38.994607   39.094263

            Adj. Volume
Date
2000-12-12    8008200.0
2000-12-13    7409800.0
2000-12-14   10047600.0
2000-12-15   27540400.0
2000-12-18   10304600.0
2000-12-19   11688200.0
2000-12-20   13344200.0
2000-12-21   11930800.0
2000-12-22    7483600.0
2000-12-26    5670000.0
2000-12-27    7711000.0
2000-12-28    5520800.0
2000-12-29    4970400.0
2001-01-02   10606000.0
2001-01-03   12469600.0
2001-01-04   14770600.0
2001-01-05    7960200.0
2001-01-08    9529200.0
2001-01-09    8516200.0
2001-01-10    7963200.0
2001-01-11    6909000.0
2001-01-12    7212000.0
2001-01-16    7163600.0
2001-01-17    7651800.0
2001-01-18    7014400.0
2001-01-19    9824200.0
2001-01-22    6874600.0
2001-01-23    7707800.0
2001-01-24    9189400.0
2001-01-25    7486800.0
...                 ...
2014-11-17   10663996.0
2014-11-18   26143194.0
2014-11-19   25400726.0
2014-11-20   13465246.0
2014-11-21   14382572.0
2014-11-24   12890423.0
2014-11-25   10741655.0
2014-11-26    9200463.0
2014-11-28   10501972.0
2014-12-01   10065657.0
2014-12-02    9878097.0
2014-12-03   15246481.0
2014-12-04   13804776.0
2014-12-05   12536928.0
2014-12-08   12805439.0
2014-12-09   25684146.0
2014-12-10   18323855.0
2014-12-11   16201423.0
2014-12-12   18431431.0
2014-12-15   23378508.0
2014-12-16   23474819.0
2014-12-17   20223938.0
2014-12-18   18030396.0
2014-12-19   24009502.0
2014-12-22   11190862.0
2014-12-23   13411064.0
2014-12-24    6405910.0
2014-12-26    6466883.0
2014-12-29    8694509.0
2014-12-30    9222049.0

[3533 rows x 12 columns]

In [3]:
# import ffn
# returns = ffn.get('aapl,msft,c,gs,ge', start='2010-01-01').to_returns().dropna()
# returns.calc_mean_var_weights().as_format('.2%')

In [4]:
#https://blog.quandl.com/api-for-housing-data

In [74]:

#
MORTG = quandl.get("FMAC/MORTG", trim_start = "2010-01-01", trim_end = "2018-03-01", authtoken=auth_tok)
UNRATE = quandl.get("FRED/UNRATE", trim_start = "2010-01-01", trim_end = "2018-03-01", authtoken=auth_tok)
#USA_NGDP_RPCH = quandl.get("ODA/USA_NGDP_RPCH", trim_start = "2010-01-01", trim_end = "2018-03-01", authtoken=auth_tok)
CPI_USA = quandl.get("RATEINF/CPI_USA", trim_start = "2000-12-12", trim_end = "2018-03-01", authtoken=auth_tok)
HPI = quandl.get("FMAC/HPI", trim_start = "2000-12-12", trim_end = "2018-03-01", authtoken=auth_tok)


#FMAC/HPI

#ODA/USA_NGDP_RPCH

#FRED/UNRATE

#print(data)

In [32]:
#quandl.get("RATEINF/CPI_USA", trim_start = "2000-12-12", trim_end = "2014-12-30", authtoken=auth_tok)

#RATEINF/INFLATION_USA

data_frames = [MORTG, UNRATE, CPI_USA]

In [69]:

data_frames[0]=data_frames[0].pct_change()
data_frames[1]=data_frames[1].pct_change()


df2 = pd.merge(data_frames[0], data_frames[1], left_index=True, right_index=True)
#df3 =  pd.merge(df2, data_frames[2], left_index=True, right_index=True)
#MORTG.join(UNRATE)

df2['month'] = pd.DatetimeIndex(df2.index).month
df2['year'] = pd.DatetimeIndex(df2.index).year



df2['month'] = pd.DatetimeIndex(df2.index).month # +1 
df2['year'] = pd.DatetimeIndex(df2.index).year

df2.head()

             Value_x   Value_y  month  year
Date
2010-01-01       NaN       NaN      1  2010
2010-02-01 -0.007952  0.000000      2  2010
2010-03-01 -0.004008  0.010204      3  2010
2010-04-01  0.026157  0.000000      4  2010
2010-05-01 -0.041176 -0.030303      5  2010

In [72]:
#CPI_USA

df7 = CPI_USA
df7= df7.pct_change()

df7['month'] = pd.DatetimeIndex(df7.index).month # +1 
df7['year'] = pd.DatetimeIndex(df7.index).year

df7

df8 = pd.merge(df2, df7, left_on=['month', 'year'],right_on=['month', 'year'])



df8.rename(columns={'Value_x':'mortgrate', 'Value_y':'unemp','Value': 'cpi' }, inplace=True)

df8.to_pickle('mortunempcpi.p')

#temp = CPI_USA['Date'].apply(np.ceil).apply(lambda x: pd.Timedelta(x, unit='D'))
#CPI_USA.index = CPI_USA.index +1

In [73]:
df8

    mortgrate     unemp  month  year       cpi
0         NaN       NaN      1  2010  0.003417
1   -0.007952  0.000000      2  2010  0.000249
2   -0.004008  0.010204      3  2010  0.004106
3    0.026157  0.000000      4  2010  0.001737
4   -0.041176 -0.030303      5  2010  0.000775
5   -0.030675 -0.020833      6  2010 -0.000976
6   -0.037975  0.000000      7  2010  0.000211
7   -0.028509  0.010638      8  2010  0.001381
8   -0.018059  0.000000      9  2010  0.000582
9   -0.027586 -0.010526     10  2010  0.001245
10   0.016548  0.042553     11  2010  0.000421
11   0.095349 -0.051020     12  2010  0.001718
12   0.010616 -0.021505      1  2011  0.004763
13   0.039916 -0.010989      2  2011  0.004931
14  -0.022222  0.000000      3  2011  0.009751
15   0.000000  0.011111      4  2011  0.006439
16  -0.041322 -0.010989      5  2011  0.004704
17  -0.028017  0.011111      6  2011 -0.001071
18   0.008869 -0.010989      7  2011  0.000886
19  -0.061538  0.000000      8  2011  0.002758
20  -0.037471  0.000000      9  2011  0.001518
21  -0.009732 -0.022222     10  2011 -0.002063
22  -0.019656 -0.022727     11  2011 -0.000844
23  -0.007519 -0.011628     12  2011 -0.002467
24  -0.010101 -0.023529      1  2012  0.004400
25  -0.007653  0.000000      2  2012  0.004403
26   0.015424 -0.012048      3  2012  0.007595
27  -0.010127  0.000000      4  2012  0.003021
28  -0.028133  0.000000      5  2012 -0.001173
29  -0.031579  0.000000      6  2012 -0.001466
..        ...       ...    ...   ...       ...
51   0.000000 -0.059701      4  2014  0.003297
52  -0.034562  0.000000      5  2014  0.003493
53  -0.007160 -0.031746      6  2014  0.001862
54  -0.007212  0.016393      7  2014 -0.000390
55  -0.002421  0.000000      8  2014 -0.001671
56   0.009709 -0.048387      9  2014  0.000753
57  -0.028846 -0.033898     10  2014 -0.002512
58  -0.009901  0.017544     11  2014 -0.005399
59  -0.035000 -0.034483     12  2014 -0.005670
60  -0.038860  0.017857      1  2015 -0.004706
61   0.000000 -0.035088      2  2015  0.004343
62   0.016173  0.000000      3  2015  0.005952
63  -0.026525 -0.018182      4  2015  0.002033
64   0.046322  0.018519      5  2015  0.005097
65   0.036458 -0.036364      6  2015  0.003503
66   0.017588 -0.018868      7  2015  0.000067
67  -0.034568 -0.019231      8  2015 -0.001416
68  -0.005115 -0.019608      9  2015 -0.001557
69  -0.023136  0.000000     10  2015 -0.000450
70   0.036842  0.000000     11  2015 -0.002111
71   0.005076  0.000000     12  2015 -0.003417
72  -0.022727 -0.020000      1  2016  0.001653
73  -0.054264  0.000000      2  2016  0.000823
74   0.008197  0.020408      3  2016  0.004306
75  -0.021680  0.000000      4  2016  0.004741
76  -0.002770 -0.060000      5  2016  0.004075
77  -0.008333  0.042553      6  2016  0.003338
78  -0.036415  0.000000      7  2016 -0.001622
79   0.000000  0.000000      8  2016  0.000839
80   0.005814  0.020408      9  2016  0.002404

[81 rows x 5 columns]

In [90]:
import pandas as pd;
from functools import reduce;
# df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Date'],
#                                             how='outer'), data_frames)

#df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Date'],how='inner'), data_frames).fillna('void')

In [93]:
HPIUS = pd.DataFrame (HPI['United States seasonaly adjusted'].pct_change())
# That is by state
HPIUS.head()


HPIUS['month'] = pd.DatetimeIndex(HPIUS.index).month # +1 
HPIUS['year'] = pd.DatetimeIndex(HPIUS.index).year

df9 = pd.merge(HPIUS, df8, left_on=['month', 'year'],right_on=['month', 'year'])
df9 = df9.dropna()

df9.rename(columns={'United States seasonaly adjusted':'HPIUS'}, inplace=True)
df9

In [101]:


df9['Date'] = df9['month'].astype(str) + ' ' +df9['year'].astype(str)
df9['Date']=  pd.to_datetime(df9['Date'], format='%m %Y')

df9.set_index('Date', inplace=True)
df9

df9.to_pickle('mortunempcpihpi.p')

In [98]:
from datetime import datetime
datestring = "3 2015"
dt = datetime.strptime(datestring, '%m %Y')
print (dt.year, dt.month, dt.day)

2015 3 1